const routes = [
  {
    path: '/',
    component: () => import('layouts/MainLayout.vue'),
    children: [
      { path: 'user-settings', name: 'user-settings', component: () => import('pages/UserSettingsPage.vue') },
      { path: 'avatar', name: 'avatar', component: () => import('pages/SettingsPage.vue') },
      { path: 'settings', redirect: { name: 'avatar' } },
      { path: 'dealz-world-home', name: 'dealz-world-home', component: () => import('pages/DealzWorldHomePage.vue') },
      { path: 'workspaces', name: 'workspaces', component: () => import('pages/TeamSpacesPage.vue') },
      { path: 'world-pipelines', redirect: { name: 'world-projects' } },
      { path: 'world-projects', name: 'world-projects', component: () => import('pages/WorldProjectsPage.vue') },
      { path: 'radars', name: 'radars', component: () => import('pages/DealzRadarPage.vue') },
      { path: 'regions', name: 'regions', component: () => import('pages/RegionsPage.vue') },
      { path: 'asset-classes', name: 'asset-classes', component: () => import('pages/AssetClassesPage.vue') },
      { path: 'industries', name: 'industries', component: () => import('pages/IndustriesPage.vue') },
      { path: 'stages', name: 'stages', component: () => import('pages/StagesPage.vue') },
      { path: 'shared-knowledge', name: 'shared-knowledge', component: () => import('pages/SharedKnowledgePage.vue') },
      { path: 'marketplace', name: 'marketplace', component: () => import('pages/MarketplacePage.vue') },
      { path: 'merch-events', name: 'merch-events', component: () => import('pages/MerchEventsPage.vue') },
      { path: 'tokenz-market-home', name: 'tokenz-market-home', component: () => import('pages/TokenzMarketHomePage.vue') },
      { path: 'tokenz-wallet', name: 'tokenz-wallet', component: () => import('pages/TokenzWalletPage.vue') },
      { path: 'tokenz-markets', name: 'tokenz-markets', component: () => import('pages/TokenzMarketsPage.vue') },
      { path: 'tokenz-vehicles', name: 'tokenz-vehicles', component: () => import('pages/TokenzVehiclesPage.vue') },
      { path: '', name: 'home', component: () => import('pages/HomePage.vue') },
      { path: 'file-system', name: 'file-system', component: () => import('pages/IndexPage.vue') },
      { path: 'pipelines', redirect: { name: 'projects' } },
      { path: 'projects', name: 'projects', component: () => import('pages/ProjectsPage.vue') },
      { path: 'opportunities', name: 'opportunities', component: () => import('pages/OpportunitiesPage.vue') },
      { path: 'funds', name: 'funds', component: () => import('pages/OpportunitiesPage.vue') },
      { path: 'rounds', name: 'rounds', component: () => import('pages/OpportunitiesPage.vue') },
      { path: 'artifacts', name: 'artifacts', component: () => import('pages/ArtifactsPage.vue') },
      { path: 'companies', name: 'companies', component: () => import('pages/CompaniesPage.vue') },
      { path: 'contacts', name: 'contacts', component: () => import('pages/ContactsPage.vue') },
      { path: 'users', name: 'users', component: () => import('pages/UsersPage.vue') },
      { path: 'notes', name: 'notes', component: () => import('pages/NotesPage.vue') },
      { path: 'tasks', name: 'tasks', component: () => import('pages/TasksPage.vue') },
      { path: 'assistants', name: 'assistants', component: () => import('pages/AssistantsPage.vue') },
      { path: 'databooks/:tableName/:recordId', name: 'databook-view', component: () => import('pages/DatabookPage.vue') },
    ],
  },

  // Always leave this as last one,
  // but you can also remove it
  {
    path: '/:catchAll(.*)*',
    component: () => import('pages/ErrorNotFound.vue'),
  },
]

export default routes
