function defineBuildingBlockDetail(detail) {
  return {
    builtFromBbs: detail.builtFromBbs || [],
    usedInShells: detail.usedInShells || [],
    usedIn: detail.usedIn || [
      detail.source ? `Primary source: ${detail.source}` : 'Primary source not yet extracted.',
    ],
    anatomy: detail.anatomy || [
      'Preserve the same typography, spacing, icon treatment, and interaction state shown in Building Blocks.',
      'Prefer changing payload and labels before changing the underlying visual structure.',
    ],
    reconstructionNotes: detail.reconstructionNotes || [
      detail.summary,
      detail.nextStep,
    ].filter(Boolean),
    ...detail,
  }
}

export const BUILDING_BLOCK_DETAILS_BY_ID = {
  fonts: defineBuildingBlockDetail({
    id: 'cmp-foundation-fonts',
    title: 'Fonts',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/css/tokens.scss + src/utils/generalSettingsCatalog.js',
    nextStep: 'Use the General Settings token layer as the single source for font family selection and shell typography inheritance.',
    summary: 'Use this for the canonical font-family system that separates title and body roles.',
    prompt: 'Render the Fonts building block from BB Shell using the General Settings token source and the live title/body font pair.',
    anatomy: ['Title font sample', 'Body font sample', 'Explicit token labels'],
    usedInShells: ['BB Shell', 'Add/Edit BB Shell', 'Add/Edit Record Shell', 'Add/Edit File Shell', 'Record Shell', 'Fork Shell', 'Ingestion Shell'],
  }),
  'type-scale': defineBuildingBlockDetail({
    id: 'cmp-foundation-type-scale',
    title: 'Type Scale',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/css/tokens.scss + src/utils/generalSettingsCatalog.js',
    nextStep: 'Use the General Settings token layer for shell type sizing instead of page-local size literals.',
    summary: 'Use this for the canonical type-size ladder across hero, body, and utility text.',
    prompt: 'Render the Type Scale building block from BB Shell using the live General Settings size tokens.',
    usedInShells: ['BB Shell', 'Add/Edit BB Shell', 'Add/Edit Record Shell', 'Add/Edit File Shell', 'Record Shell', 'Fork Shell', 'Ingestion Shell'],
  }),
  'font-weights': defineBuildingBlockDetail({
    id: 'cmp-foundation-font-weights',
    title: 'Font Weights',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/css/tokens.scss + src/utils/generalSettingsCatalog.js',
    nextStep: 'Use the General Settings token layer for weight changes instead of hardcoded numeric values in local components.',
    summary: 'Use this for the canonical weight ladder from light through black.',
    prompt: 'Render the Font Weights building block from BB Shell using the live General Settings weight tokens.',
    usedInShells: ['BB Shell', 'Add/Edit BB Shell', 'Add/Edit Record Shell', 'Add/Edit File Shell', 'Record Shell', 'Fork Shell', 'Ingestion Shell'],
  }),
  colors: defineBuildingBlockDetail({
    id: 'cmp-foundation-colors',
    title: 'Colors',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/css/tokens.scss + src/utils/generalSettingsCatalog.js',
    nextStep: 'Use the General Settings token layer for shell and component colors instead of drifting local hex values.',
    summary: 'Use this for the canonical text, brand, surface, and border color family.',
    prompt: 'Render the Colors building block from BB Shell using the live General Settings color tokens.',
    usedInShells: ['BB Shell', 'Add/Edit BB Shell', 'Add/Edit Record Shell', 'Add/Edit File Shell', 'Record Shell', 'Fork Shell', 'Ingestion Shell'],
  }),
  surfaces: defineBuildingBlockDetail({
    id: 'cmp-foundation-surfaces',
    title: 'Surfaces',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/css/tokens.scss + src/utils/generalSettingsCatalog.js',
    nextStep: 'Use the General Settings token layer for surface backgrounds and overlay states.',
    summary: 'Use this for the canonical surface family that shells and cards sit on top of.',
    prompt: 'Render the Surfaces building block from BB Shell using the live General Settings surface tokens.',
    usedInShells: ['BB Shell', 'Add/Edit BB Shell', 'Add/Edit Record Shell', 'Add/Edit File Shell', 'Record Shell', 'Fork Shell', 'Ingestion Shell'],
  }),
  borders: defineBuildingBlockDetail({
    id: 'cmp-foundation-borders',
    title: 'Borders',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/css/tokens.scss + src/utils/generalSettingsCatalog.js',
    nextStep: 'Use the General Settings token layer for shell and control border treatment.',
    summary: 'Use this for the canonical border language across cards, controls, and panels.',
    prompt: 'Render the Borders building block from BB Shell using the live General Settings border tokens.',
    usedInShells: ['BB Shell', 'Add/Edit BB Shell', 'Add/Edit Record Shell', 'Add/Edit File Shell', 'Record Shell', 'Fork Shell', 'Ingestion Shell'],
  }),
  radius: defineBuildingBlockDetail({
    id: 'cmp-foundation-radius',
    title: 'Radius',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/css/tokens.scss + src/utils/generalSettingsCatalog.js',
    nextStep: 'Use the General Settings token layer for corner treatments instead of per-page radius literals.',
    summary: 'Use this for the canonical corner-radius ladder from sharp shells to pill controls.',
    prompt: 'Render the Radius building block from BB Shell using the live General Settings radius tokens.',
    usedInShells: ['BB Shell', 'Add/Edit BB Shell', 'Add/Edit Record Shell', 'Add/Edit File Shell', 'Record Shell', 'Fork Shell', 'Ingestion Shell'],
  }),
  shadows: defineBuildingBlockDetail({
    id: 'cmp-foundation-shadows',
    title: 'Shadows',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/css/tokens.scss + src/utils/generalSettingsCatalog.js',
    nextStep: 'Use the General Settings token layer for elevation and focus shadows.',
    summary: 'Use this for the canonical shadow/elevation system across labels, cards, and controls.',
    prompt: 'Render the Shadows building block from BB Shell using the live General Settings shadow tokens.',
    usedInShells: ['BB Shell', 'Add/Edit BB Shell', 'Add/Edit Record Shell', 'Add/Edit File Shell', 'Record Shell', 'Fork Shell', 'Ingestion Shell'],
  }),
  spacing: defineBuildingBlockDetail({
    id: 'cmp-foundation-spacing',
    title: 'Spacing',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/css/tokens.scss + src/utils/generalSettingsCatalog.js',
    nextStep: 'Use the General Settings token layer for spacing rhythm instead of arbitrary pixel values.',
    summary: 'Use this for the canonical spacing ladder that controls shell rhythm and component density.',
    prompt: 'Render the Spacing building block from BB Shell using the live General Settings spacing tokens.',
    usedInShells: ['BB Shell', 'Add/Edit BB Shell', 'Add/Edit Record Shell', 'Add/Edit File Shell', 'Record Shell', 'Fork Shell', 'Ingestion Shell'],
  }),
  'icon-sizing': defineBuildingBlockDetail({
    id: 'cmp-foundation-icon-sizing',
    title: 'Icon Sizing',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/css/tokens.scss + src/utils/generalSettingsCatalog.js',
    nextStep: 'Use the General Settings token layer for icon sizes across buttons, chips, and shell controls.',
    summary: 'Use this for the canonical icon-size ladder.',
    prompt: 'Render the Icon Sizing building block from BB Shell using the live General Settings icon size tokens.',
    usedInShells: ['BB Shell', 'Add/Edit BB Shell', 'Add/Edit Record Shell', 'Add/Edit File Shell', 'Record Shell', 'Fork Shell', 'Ingestion Shell'],
  }),
  'formatting-rules': defineBuildingBlockDetail({
    id: 'cmp-foundation-formatting-rules',
    title: 'Formatting Rules',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/utils/generalSettingsCatalog.js',
    nextStep: 'Promote number/date formatting into General Settings ownership instead of leaving formatting examples implied.',
    summary: 'Use this for the current number, currency, percent, date, and time formatting language.',
    prompt: 'Render the Formatting Rules building block from BB Shell using the canonical number/date formatting examples.',
    usedInShells: ['BB Shell', 'Add/Edit BB Shell', 'Add/Edit Record Shell', 'Add/Edit File Shell', 'Record Shell', 'Fork Shell', 'Ingestion Shell'],
  }),
  'motion-rules': defineBuildingBlockDetail({
    id: 'cmp-foundation-motion-rules',
    title: 'Motion Rules',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/utils/generalSettingsCatalog.js',
    nextStep: 'Keep shell motion purposeful and token-driven instead of page-local animation timing guesses.',
    summary: 'Use this for the current motion timing language across quick, standard, and emphasis interactions.',
    prompt: 'Render the Motion Rules building block from BB Shell using the canonical motion timing samples.',
    usedInShells: ['BB Shell', 'Add/Edit BB Shell', 'Add/Edit Record Shell', 'Add/Edit File Shell', 'Record Shell', 'Fork Shell', 'Ingestion Shell'],
  }),
  'home-dashboard': defineBuildingBlockDetail({
    id: 'cmp-home-dashboard',
    title: 'Home Dashboard',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/HomeDashboardHero.vue',
    nextStep: 'Reuse the shared hero directly and vary only the explicit home-dashboard payload.',
    summary: 'Use this for the live Home dashboard hero surface with overview count, top stats, workspace root, and signal chips.',
    prompt: 'Render the Home Dashboard component from Building Blocks by reusing the shared HomeDashboardHero component directly instead of recreating the hero layout locally.',
    usedIn: ['Home page hero surface', 'Building Blocks file component catalog'],
    usedInShells: ['BB Shell'],
    builtFromBbs: ['page-title-crumb', 'l3-box'],
    anatomy: ['Breadcrumb row above the page title when used as a page header counterpart', 'Large overview count', 'Three stat blocks', 'Side panels for root path and active signal chips'],
  }),
  'page-title-crumb': defineBuildingBlockDetail({
    id: 'cmp-page-title-crumb',
    title: 'Page Title / Crumb',
    status: 'extract',
    statusLabel: 'Extract Next',
    source: 'Local sample in src/pages/ComponentsShellPage.vue',
    nextStep: 'Extract the shared page-title and crumb block so shell pages stop hand-rendering this header.',
    summary: 'Use this for page headers that show the current area plus the main page title.',
    prompt: 'Render the Page Title / Crumb component from Building Blocks with a breadcrumb row above a large page title, using the same typography and spacing as the canonical component.',
    usedIn: ['Page-level shell headers', 'Any route-mounted page that needs breadcrumb plus title treatment'],
    usedInShells: ['BB Shell', 'Add/Edit BB Shell', 'Add/Edit Record Shell', 'Add/Edit File Shell', 'Record Shell', 'Fork Shell', 'Ingestion Shell'],
    builtFromBbs: ['fonts', 'type-scale', 'font-weights', 'colors', 'spacing'],
    anatomy: ['Muted breadcrumb row', 'Large title row', 'Title font with tight tracking'],
  }),
  'page-back-symbol': defineBuildingBlockDetail({
    id: 'cmp-page-back-symbol',
    title: 'Page Back Symbol',
    status: 'extract',
    statusLabel: 'Extract Next',
    source: 'Local sample in src/pages/ComponentsShellPage.vue',
    nextStep: 'Extract the shared back control so shell headers use one canonical arrow-plus-Back button.',
    summary: 'Use this for compact back navigation inside shell headers and detail surfaces.',
    prompt: 'Render the Page Back Symbol from Building Blocks exactly, using the same circular neutral button treatment and arrow icon.',
    usedIn: ['Shell header left cluster', 'Pages with explicit back navigation'],
    usedInShells: ['BB Shell', 'Add/Edit BB Shell', 'Add/Edit Record Shell', 'Add/Edit File Shell', 'Record Shell', 'Fork Shell', 'Ingestion Shell'],
    builtFromBbs: ['colors', 'borders', 'radius', 'spacing', 'icon-sizing'],
    anatomy: ['Left-pointing arrow icon', 'Back label', 'Compact inline spacing'],
  }),
  'b10-logo': defineBuildingBlockDetail({
    id: 'cmp-b10-logo',
    title: 'B10 Logo',
    status: 'extract',
    statusLabel: 'Extract Next',
    source: 'Shared logo asset with local wrapper in src/pages/ComponentsShellPage.vue',
    nextStep: 'Wrap the live header logo treatment into one shared logo component instead of repeating its container markup.',
    summary: 'Use this for compact brand badges or temporary logo placeholders.',
    prompt: 'Render the B10 Logo from Building Blocks exactly as the compact black badge with the same title-font styling.',
    usedInShells: ['BB Shell', 'Add/Edit BB Shell', 'Add/Edit Record Shell', 'Add/Edit File Shell', 'Record Shell', 'Fork Shell', 'Ingestion Shell'],
    builtFromBbs: ['fonts', 'colors', 'radius', 'spacing'],
  }),
  'plus-icon': defineBuildingBlockDetail({
    id: 'cmp-plus-icon',
    title: 'Plus Icon',
    status: 'extract',
    statusLabel: 'Extract Next',
    source: 'Local sample in src/pages/ComponentsShellPage.vue',
    nextStep: 'Extract the electric blue standalone add chip so widget and shell add controls stop drifting.',
    summary: 'Use this for isolated add actions where only the icon should show.',
    prompt: 'Render the Plus Icon component from Building Blocks exactly, using the same electric-blue circular button with white plus icon.',
    usedInShells: ['BB Shell', 'Add/Edit BB Shell', 'Add/Edit Record Shell', 'Add/Edit File Shell'],
    builtFromBbs: ['colors', 'radius', 'icon-sizing'],
  }),
  'plus-with-label': defineBuildingBlockDetail({
    id: 'cmp-plus-with-label',
    title: 'Plus With Label',
    status: 'extract',
    statusLabel: 'Extract Next',
    source: 'Local sample in src/pages/ComponentsShellPage.vue',
    nextStep: 'Extract the labeled add control so file-toolbar and shell add buttons can share one component with payload-only label changes.',
    summary: 'Use this for add actions that need icon plus text in one control.',
    prompt: 'Render the Plus With Label component from Building Blocks exactly, using the same electric-blue button, white plus icon, and title-font label treatment.',
    usedInShells: ['BB Shell', 'Add/Edit BB Shell', 'Add/Edit Record Shell', 'Add/Edit File Shell', 'File Shell', 'Record Shell'],
    builtFromBbs: ['plus-icon', 'fonts', 'font-weights', 'colors', 'spacing'],
  }),
  'bb-tile-header': defineBuildingBlockDetail({
    id: 'cmp-bb-tile-header',
    title: 'BB Tile Header',
    status: 'extract',
    statusLabel: 'Extract Next',
    source: 'Local pattern in src/components/BuildingBlockPreviewTile.vue',
    nextStep: 'Extract the tile header so Building Blocks and BB Shell share one canonical top-row component.',
    summary: 'Use this for the top row of BB tiles with title, collapse arrow, copy action, and view action.',
    prompt: 'Render the BB Tile Header from Building Blocks using the same cool title type, collapse arrow, copy action, and eye action aligned in one compact top row.',
    usedIn: ['BB Shell tile top row', 'Building Blocks tile top row'],
    usedInShells: ['BB Shell', 'Add/Edit BB Shell'],
    builtFromBbs: ['eye-icon', 'font-weights', 'colors', 'spacing'],
    anatomy: ['Strong title-style text on the left', 'Collapse / expand arrow inline with the title', 'Copy icon action', 'Eye icon action'],
  }),
  'live-action-l1': defineBuildingBlockDetail({
    id: 'cmp-live-action-l1',
    title: 'Live Action L1',
    status: 'extract',
    statusLabel: 'Extract Next',
    source: 'Local sample in src/pages/ComponentsShellPage.vue',
    nextStep: 'Extract the shell header selector so Record Shell, Fork Shell, and future shells use one live-action control.',
    summary: 'Use this for shell-level live source selectors that sit in the top center and switch the active L1 context.',
    prompt: 'Render the Live Action L1 control from Building Blocks exactly, using the same Live Link label, black value chip, and chevron treatment as the canonical shell selector.',
    usedInShells: ['Record Shell', 'Fork Shell'],
    builtFromBbs: ['fonts', 'font-weights', 'colors', 'borders', 'radius', 'spacing'],
  }),
  'file-shell-title-row': defineBuildingBlockDetail({
    id: 'cmp-file-shell-title-row',
    title: 'File Shell Title Row',
    status: 'extract',
    statusLabel: 'Extract Next',
    source: 'Local shell-header pattern across route-mounted file pages',
    nextStep: 'Extract the file shell title row so file surfaces share one header contract before payload is swapped.',
    summary: 'Use this for the top title row on file-level shells where the page title, back cluster, and shell controls align in one header lane.',
    prompt: 'Render the File Shell Title Row from Building Blocks using the canonical shell-header composition, without inventing local header spacing.',
    usedInShells: ['File Shell', 'BB Shell'],
    builtFromBbs: ['page-back-symbol', 'page-title-crumb', 'colors', 'spacing'],
    anatomy: ['Back or shell-left cluster', 'Page title / crumb treatment', 'Optional shell action lane'],
  }),
  'record-shell-title-row': defineBuildingBlockDetail({
    id: 'cmp-record-shell-title-row',
    title: 'Record Shell Title Row',
    status: 'extract',
    statusLabel: 'Extract Next',
    source: 'Local shell-header pattern in src/pages/RecordShellPage.vue',
    nextStep: 'Extract the record shell title row so record surfaces stop hand-rendering their top header treatment.',
    summary: 'Use this for the top title row on record-level shells where back navigation, record title, and shell actions live together.',
    prompt: 'Render the Record Shell Title Row from Building Blocks using the same header hierarchy and spacing as the canonical record-shell title row.',
    usedInShells: ['Record Shell'],
    builtFromBbs: ['page-back-symbol', 'page-title-crumb', 'live-action-l1', 'colors', 'spacing'],
    anatomy: ['Back cluster', 'Record title treatment', 'Right-side action cluster'],
  }),
  'b10-button': defineBuildingBlockDetail({
    id: 'cmp-b10-button',
    title: 'B10 Button',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/buttons/B10Button.vue',
    nextStep: 'Reuse this component directly and vary only payload props such as label and variant.',
    summary: 'Use this for canonical B10 primary and neutral action buttons.',
    prompt: 'Render the B10 Button component from Building Blocks using the real shared B10Button variants rather than recreating local button styles.',
    usedInShells: ['BB Shell', 'Add/Edit BB Shell', 'Add/Edit Record Shell', 'Add/Edit File Shell', 'Record Shell', 'Fork Shell', 'Ingestion Shell'],
    builtFromBbs: ['fonts', 'font-weights', 'colors', 'radius', 'spacing'],
  }),
  'b10-icon-button': defineBuildingBlockDetail({
    id: 'cmp-b10-icon-button',
    title: 'B10 Icon Button',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/buttons/B10IconButton.vue',
    nextStep: 'Reuse this component directly and vary only icon and variant props.',
    summary: 'Use this for canonical icon-only actions that should come from the B10 button system.',
    prompt: 'Render the B10 Icon Button component from Building Blocks using the shared B10IconButton component and its existing variants.',
    usedInShells: ['BB Shell', 'Add/Edit BB Shell', 'Add/Edit Record Shell', 'Add/Edit File Shell', 'Record Shell', 'Fork Shell', 'Ingestion Shell'],
    builtFromBbs: ['colors', 'radius', 'icon-sizing', 'spacing'],
  }),
  'main-menu-icon': defineBuildingBlockDetail({
    id: 'cmp-main-menu-icon',
    title: 'Main Menu Icon',
    status: 'extract',
    statusLabel: 'Extract Next',
    source: 'Local sample from src/layouts/MainLayout.vue header menu button',
    nextStep: 'Extract the top-left menu trigger so shell headers use one canonical drawer-toggle control.',
    summary: 'Use this for the compact menu trigger in the top-left shell header.',
    prompt: 'Render the Main Menu Icon from Building Blocks using the same flat round menu button treatment as the shell header drawer trigger.',
    usedInShells: ['Main Layout'],
    builtFromBbs: ['colors', 'icon-sizing'],
  }),
  'file-dashboard': defineBuildingBlockDetail({
    id: 'cmp-file-dashboard',
    title: 'File Dashboard',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/FilePageHeroDashboard.vue',
    nextStep: 'Reuse the shared dashboard component and only swap explicit payload data.',
    summary: 'Use this for file-level hero dashboards showing title, copy, stats, and health.',
    prompt: 'Render the File Dashboard component from Building Blocks using the real FilePageHeroDashboard surface, preserving its hero, stats, and health structure.',
    usedInShells: ['BB Shell', 'File Shell'],
    builtFromBbs: ['l3-box', 'colors', 'surfaces', 'shadows', 'spacing'],
  }),
  'l3-box': defineBuildingBlockDetail({
    id: 'cmp-l3-box',
    title: 'L3 Box',
    status: 'extract',
    statusLabel: 'Extract Next',
    source: 'Local sample in src/pages/ComponentsShellPage.vue',
    nextStep: 'Extract the metric card so dashboard stat strips can use one canonical stat-box component.',
    summary: 'Use this for the standalone L3 stat card that appears inside the shell dashboard metrics strip.',
    prompt: 'Render the L3 Box from Building Blocks exactly, using the same compact dashboard stat-card treatment with label, large value, and caption.',
    usedInShells: ['BB Shell', 'File Shell', 'Record Shell'],
    builtFromBbs: ['type-scale', 'font-weights', 'colors', 'surfaces', 'borders', 'radius', 'spacing'],
  }),
  'file-toolbar': defineBuildingBlockDetail({
    id: 'cmp-file-toolbar',
    title: 'File Toolbar',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/FilePageToolbar.vue',
    nextStep: 'Reuse the shared toolbar directly and vary only its explicit props and payload.',
    summary: 'Use this for the top toolbar inside file pages with add, search, and view controls.',
    prompt: 'Render the File Toolbar component from Building Blocks using the real FilePageToolbar component, keeping its existing add, search, and view-toggle layout.',
    usedInShells: ['BB Shell', 'File Shell'],
    builtFromBbs: ['plus-with-label', 'b10-icon-button', 'colors', 'surfaces', 'borders', 'radius', 'spacing'],
  }),
  'record-dashboard': defineBuildingBlockDetail({
    id: 'cmp-record-dashboard',
    title: 'Record Dashboard',
    status: 'extract',
    statusLabel: 'Extract Next',
    source: 'Local launchpad/dashboard pattern in src/components/FilePageShell.vue and src/pages/RecordShellPage.vue',
    nextStep: 'Extract the record dashboard surface so record shells share one canonical hero/dashboard treatment.',
    summary: 'Use this for record-level hero or launchpad surfaces that summarize the active record and its key actions.',
    prompt: 'Render the Record Dashboard from Building Blocks using the canonical record-shell hero/dashboard surface rather than a local one-off record header.',
    usedInShells: ['Record Shell'],
    builtFromBbs: ['page-title-crumb', 'b10-button', 'record-hero-field-card', 'record-context-panel', 'record-feed-panel', 'colors', 'surfaces', 'shadows', 'spacing'],
    anatomy: ['Record eyebrow', 'Record title', 'Supporting summary copy', 'Primary record action lane'],
  }),
  'record-hero-field-card': defineBuildingBlockDetail({
    id: 'cmp-record-hero-field-card',
    title: 'Record Hero Field Card',
    status: 'extract',
    statusLabel: 'Extract Next',
    source: 'src/pages/RecordShellPage.vue',
    nextStep: 'Extract the record hero field card so record summary cards share one canonical shell component.',
    summary: 'Use this for the record-shell hero cards that show a label, descriptor, value, and optional status icon.',
    prompt: 'Render the Record Hero Field Card from Building Blocks using the same record-shell hero card treatment, including label, descriptor, value, and optional status icon.',
    usedInShells: ['Record Shell'],
    builtFromBbs: ['type-scale', 'font-weights', 'colors', 'surfaces', 'borders', 'radius', 'spacing', 'icon-sizing'],
    anatomy: ['Field label', 'Field description', 'Primary value', 'Optional status icon'],
  }),
  'record-context-panel': defineBuildingBlockDetail({
    id: 'cmp-record-context-panel',
    title: 'Record Context Panel',
    status: 'extract',
    statusLabel: 'Extract Next',
    source: 'src/pages/RecordShellPage.vue',
    nextStep: 'Extract the record context panel so notes and related-artifact context share one canonical side panel.',
    summary: 'Use this for the tabbed record context surface that shows latest notes and related artifacts.',
    prompt: 'Render the Record Context Panel from Building Blocks using the same tabbed side-panel treatment from Record Shell, including context tabs, list rows, and empty states.',
    usedInShells: ['Record Shell'],
    builtFromBbs: ['colors', 'surfaces', 'borders', 'radius', 'spacing', 'toggle-row-icons'],
    anatomy: ['Context tabs', 'Context list rows', 'Context meta line', 'Empty state copy'],
  }),
  'record-feed-panel': defineBuildingBlockDetail({
    id: 'cmp-record-feed-panel',
    title: 'Record Feed Panel',
    status: 'extract',
    statusLabel: 'Extract Next',
    source: 'src/pages/RecordShellPage.vue',
    nextStep: 'Extract the record feed panel so feed tabs and entries stop being record-shell-local markup.',
    summary: 'Use this for the right-side record feed surface with feed tabs, entries, and open-log actions.',
    prompt: 'Render the Record Feed Panel from Building Blocks using the same Record Shell feed panel with header, tab row, feed entries, and open-log action.',
    usedInShells: ['Record Shell'],
    builtFromBbs: ['colors', 'surfaces', 'borders', 'radius', 'spacing', 'eye-icon', 'toggle-row-icons'],
    anatomy: ['Feed header', 'Feed tabs', 'Feed entry row', 'Open-log action'],
  }),
  'l2-toolbar': defineBuildingBlockDetail({
    id: 'cmp-l2-toolbar',
    title: 'L2 Toolbar',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/ShellSectionToolbar.vue',
    nextStep: 'Reuse the shared section toolbar directly and vary only section items and selected payload.',
    summary: 'Use this for section switching across General, KDB, System, and similar level-2 groupings.',
    prompt: 'Render the L2 Toolbar component from Building Blocks using the real ShellSectionToolbar component with the same compact section-chip treatment.',
    usedInShells: ['BB Shell', 'File Shell', 'Record Shell'],
    builtFromBbs: ['colors', 'surfaces', 'borders', 'radius', 'spacing'],
  }),
  'l2-settings-menu': defineBuildingBlockDetail({
    id: 'cmp-l2-settings-menu',
    title: 'L2 Settings Menu',
    status: 'extract',
    statusLabel: 'Extract Next',
    source: 'Local sample in src/pages/ComponentsShellPage.vue',
    nextStep: 'Extract the compact grouped settings panel so all L2 settings menus stop being page-specific markup.',
    summary: 'Use this for compact shell settings menus like Hero Fields where grouped options can be expanded or collapsed.',
    prompt: 'Render the L2 Settings Menu from Building Blocks using the same compact panel, grouped rows, checkboxes, and expand/collapse treatment as the canonical menu sample.',
    usedInShells: ['BB Shell', 'File Shell', 'Record Shell'],
    builtFromBbs: ['toggle-row-icons', 'colors', 'surfaces', 'borders', 'radius', 'spacing'],
  }),
  'widget-settings-menu': defineBuildingBlockDetail({
    id: 'cmp-widget-settings-menu',
    title: 'Widget Settings Menu',
    status: 'extract',
    statusLabel: 'Extract Next',
    source: 'Local sample in src/pages/ComponentsShellPage.vue',
    nextStep: 'Extract the widget settings panel so grouped widget menus reuse one floating settings component.',
    summary: 'Use this for the floating widget settings panel with grouped rows, checkboxes, and reorder chevrons.',
    prompt: 'Render the Widget Settings Menu from Building Blocks using the same dark floating panel, grouped section toggle, row labels, checkboxes, and reorder chevrons.',
    usedInShells: ['BB Shell', 'File Shell', 'Record Shell'],
    builtFromBbs: ['toggle-row-icons', 'colors', 'surfaces', 'borders', 'radius', 'shadows', 'spacing'],
  }),
  'dialog-shell-frame': defineBuildingBlockDetail({
    id: 'cmp-dialog-shell-frame',
    title: 'Dialog Shell Frame',
    status: 'extract',
    statusLabel: 'Extract Next',
    source: 'src/components/AddEditRecordShellDialog.vue',
    nextStep: 'Extract the shared dialog frame so add/edit shells inherit one modal container contract.',
    summary: 'Use this for the outer dialog container that wraps add/edit shell content.',
    prompt: 'Render the Dialog Shell Frame from Building Blocks using the same shell dialog container, radius, border, and inset layout as the canonical add/edit shell.',
    usedInShells: ['Add/Edit Record Shell', 'Add/Edit File Shell', 'Add/Edit BB Shell'],
    builtFromBbs: ['surfaces', 'borders', 'radius', 'spacing', 'mini-scrollbar'],
    anatomy: ['Dialog card container', 'Header region', 'Scrollable body region', 'Footer/action region'],
  }),
  'dialog-shell-title-row': defineBuildingBlockDetail({
    id: 'cmp-dialog-shell-title-row',
    title: 'Dialog Shell Title Row',
    status: 'extract',
    statusLabel: 'Extract Next',
    source: 'src/components/AddEditRecordShellDialog.vue',
    nextStep: 'Extract the title row so dialog shells share one close/title/action header lane.',
    summary: 'Use this for the top row inside add/edit shell dialogs.',
    prompt: 'Render the Dialog Shell Title Row from Building Blocks using the canonical add/edit shell title row and close-control alignment.',
    usedInShells: ['Add/Edit Record Shell', 'Add/Edit File Shell', 'Add/Edit BB Shell'],
    builtFromBbs: ['page-title-crumb', 'colors', 'spacing'],
    anatomy: ['Eyebrow or shell label', 'Main title', 'Optional header actions', 'Close icon button'],
  }),
  'dialog-shell-footer': defineBuildingBlockDetail({
    id: 'cmp-dialog-shell-footer',
    title: 'Dialog Shell Footer',
    status: 'extract',
    statusLabel: 'Extract Next',
    source: 'src/components/AddEditRecordShellDialog.vue',
    nextStep: 'Extract the footer/action lane so save, cancel, and related shell actions use one dialog-footer contract.',
    summary: 'Use this for the footer action row inside add/edit shell dialogs.',
    prompt: 'Render the Dialog Shell Footer from Building Blocks using the canonical save/cancel action lane from the add/edit shell family.',
    usedInShells: ['Add/Edit Record Shell', 'Add/Edit File Shell', 'Add/Edit BB Shell'],
    builtFromBbs: ['b10-button', 'colors', 'surfaces', 'borders', 'radius', 'spacing'],
    anatomy: ['Footer container', 'Primary action', 'Secondary action', 'Optional status/help copy'],
  }),
  'main-menu-row': defineBuildingBlockDetail({
    id: 'cmp-main-menu-row',
    title: 'Main Menu Row',
    status: 'extract',
    statusLabel: 'Extract Next',
    source: 'Local sample from src/layouts/MainLayout.vue drawer rows',
    nextStep: 'Extract the drawer item row so navigation entries share one canonical icon-label row structure.',
    summary: 'Use this for standard main menu file rows inside the left drawer.',
    prompt: 'Render the Main Menu Row from Building Blocks using the same left-drawer icon and label treatment as the canonical nav row.',
    usedInShells: ['Main Layout'],
    builtFromBbs: ['main-menu-icon', 'fonts', 'colors', 'spacing'],
  }),
  'main-menu-subgroup-row': defineBuildingBlockDetail({
    id: 'cmp-main-menu-subgroup-row',
    title: 'Main Menu Subgroup Row',
    status: 'extract',
    statusLabel: 'Extract Next',
    source: 'Local sample from src/layouts/MainLayout.vue drawer subgroup toggles',
    nextStep: 'Extract the subgroup toggle row so drawer section headings share one canonical expand-collapse treatment.',
    summary: 'Use this for grouped left-drawer subsection rows like Shells and workspace groupings.',
    prompt: 'Render the Main Menu Subgroup Row from Building Blocks using the same subgroup title plus expand-collapse chevron treatment as the canonical drawer subgroup row.',
    usedInShells: ['Main Layout'],
    builtFromBbs: ['toggle-row-icons', 'fonts', 'colors', 'spacing'],
  }),
  'eye-icon': defineBuildingBlockDetail({
    id: 'cmp-eye-icon',
    title: 'Eye Icon',
    status: 'extract',
    statusLabel: 'Extract Next',
    source: 'Local sample in src/pages/ComponentsShellPage.vue',
    nextStep: 'Extract the lightweight view-action icon button so cards and rows stop restyling visibility controls.',
    summary: 'Use this for record/view actions in cards and tables where a lightweight visibility control is needed.',
    prompt: 'Render the Eye Icon from Building Blocks using the same lightweight visibility button treatment as the canonical row-view control.',
    usedInShells: ['BB Shell', 'File Shell', 'Record Shell'],
    builtFromBbs: ['colors', 'icon-sizing'],
  }),
  'edit-button': defineBuildingBlockDetail({
    id: 'cmp-edit-button',
    title: 'Edit Button',
    status: 'extract',
    statusLabel: 'Extract Next',
    source: 'Local sample in src/pages/ComponentsShellPage.vue',
    nextStep: 'Extract the compact blue edit control so row and card edit actions use one shared component.',
    summary: 'Use this for compact edit actions in cards and row controls where the blue edit icon treatment is expected.',
    prompt: 'Render the Edit Button from Building Blocks using the same compact blue edit icon treatment as the canonical row-edit control.',
    usedInShells: ['BB Shell', 'File Shell', 'Record Shell'],
    builtFromBbs: ['colors', 'icon-sizing', 'radius'],
  }),
  'mini-scrollbar': defineBuildingBlockDetail({
    id: 'cmp-mini-scrollbar',
    title: 'Mini Scrollbar',
    status: 'extract',
    statusLabel: 'Extract Next',
    source: 'Local sample matching shell mini-scrollbar treatment',
    nextStep: 'Extract the narrow black scrollbar styling so dense shells and tables share one overflow control language.',
    summary: 'Use this for the thin black scrollbar treatment that appears in dense shell panels.',
    prompt: 'Render the Mini Scrollbar from Building Blocks using the same narrow black track-and-thumb treatment as the canonical shell overflow control.',
    usedInShells: ['BB Shell', 'Add/Edit BB Shell', 'Add/Edit Record Shell', 'Add/Edit File Shell', 'Record Shell', 'File Shell'],
    builtFromBbs: ['colors'],
  }),
  'toggle-row-icons': defineBuildingBlockDetail({
    id: 'cmp-toggle-row-icons',
    title: 'Toggle / Row Icons',
    status: 'extract',
    statusLabel: 'Extract Next',
    source: 'Local sample in src/pages/ComponentsShellPage.vue',
    nextStep: 'Extract the toggle and row-chevron micro-controls so settings lists and shell rows use the same icon language.',
    summary: 'Use this for inline subgroup toggles and row ordering chevrons across shell menus and settings lists.',
    prompt: 'Render the Toggle / Row Icons from Building Blocks using the same inline label-plus-chevron and compact row-chevron treatments as the canonical controls.',
    usedInShells: ['BB Shell', 'File Shell', 'Record Shell'],
    builtFromBbs: ['colors', 'icon-sizing'],
  }),
  'shell-open-dialog-button': defineBuildingBlockDetail({
    id: 'cmp-shell-open-dialog-button',
    title: 'Shell Open Dialog Button',
    status: 'extract',
    statusLabel: 'Extract Next',
    source: 'Route-backed shell reopen buttons across MainLayout and shell pages',
    nextStep: 'Extract the shell reopen/open-dialog button so shell pages use one route-aware launch control.',
    summary: 'Use this for shell-specific buttons that reopen or launch the active shell dialog.',
    prompt: 'Render the Shell Open Dialog Button from Building Blocks using the canonical shell launch button treatment with route-aware behavior.',
    usedInShells: ['Add/Edit Record Shell', 'Add/Edit File Shell', 'Add/Edit BB Shell', 'Fork Shell'],
    builtFromBbs: ['b10-button'],
    anatomy: ['Button container', 'Action label', 'Shell-aware open behavior'],
  }),
  'record-shell-launchpad': defineBuildingBlockDetail({
    id: 'cmp-record-shell-launchpad',
    title: 'Record Shell Launchpad',
    status: 'extract',
    statusLabel: 'Extract Next',
    source: 'src/components/FilePageShell.vue',
    nextStep: 'Extract the record-shell launchpad so create-entry route surfaces share one canonical pre-dialog panel.',
    summary: 'Use this for the record-shell launchpad panel that explains the create flow and provides the primary create action.',
    prompt: 'Render the Record Shell Launchpad from Building Blocks using the same eyebrow, title, explanatory copy, and primary create button treatment as the current shell launchpad.',
    usedInShells: ['Record Shell'],
    builtFromBbs: ['b10-button', 'colors', 'surfaces', 'borders', 'radius', 'spacing'],
    anatomy: ['Eyebrow', 'Launch title', 'Instructional copy', 'Primary create action'],
  }),
  'file-filter-menu': defineBuildingBlockDetail({
    id: 'cmp-file-filter-menu',
    title: 'File Filter Menu',
    status: 'extract',
    statusLabel: 'Extract Next',
    source: 'src/components/FilePageShell.vue',
    nextStep: 'Extract the file filter menu so section/token filtering stops being file-shell-local markup.',
    summary: 'Use this for the file-shell filter menu with grouped sections, token rows, and checkboxes.',
    prompt: 'Render the File Filter Menu from Building Blocks using the same grouped filter panel, section headings, token rows, and checkbox treatment as the current file shell.',
    usedInShells: ['File Shell', 'BB Shell'],
    builtFromBbs: ['toggle-row-icons', 'colors', 'surfaces', 'borders', 'radius', 'spacing'],
    anatomy: ['Filter panel title', 'Grouped section headings', 'Token rows', 'Checkbox controls'],
  }),
  'fork-selector-surface': defineBuildingBlockDetail({
    id: 'cmp-fork-selector-surface',
    title: 'Fork Selector Surface',
    status: 'extract',
    statusLabel: 'Extract Next',
    source: 'src/pages/ForkShellPage.vue',
    nextStep: 'Extract the fork-shell selector surface so branchable shell selection uses one canonical top selector treatment.',
    summary: 'Use this for the black value-chip selector that sits above the fork shell card and switches the active branchable L1.',
    prompt: 'Render the Fork Selector Surface from Building Blocks using the same top selector surface from Fork Shell, including the hover label and black selected-value chip.',
    usedInShells: ['Fork Shell'],
    builtFromBbs: ['live-action-l1', 'colors', 'spacing'],
    anatomy: ['Hover label', 'Selected value chip', 'Dropdown surface'],
  }),
  'fork-branch-card': defineBuildingBlockDetail({
    id: 'cmp-fork-branch-card',
    title: 'Fork Branch Card',
    status: 'extract',
    statusLabel: 'Extract Next',
    source: 'src/pages/ForkShellPage.vue',
    nextStep: 'Extract the fork branch card so branch choices use one canonical branch-choice tile.',
    summary: 'Use this for the selectable branch cards inside Fork Shell.',
    prompt: 'Render the Fork Branch Card from Building Blocks using the same selectable branch tile treatment from Fork Shell.',
    usedInShells: ['Fork Shell'],
    builtFromBbs: ['colors', 'surfaces', 'borders', 'radius', 'spacing', 'font-weights'],
    anatomy: ['Branch card container', 'Branch title', 'Hover/focus state'],
  }),
  'shell-route-empty-view': defineBuildingBlockDetail({
    id: 'cmp-shell-route-empty-view',
    title: 'Shell Route Empty View',
    status: 'extract',
    statusLabel: 'Extract Next',
    source: 'Blank mounted shell routes before or after dialog open state',
    nextStep: 'Extract the mounted empty shell state so route-backed shell pages share one neutral base state.',
    summary: 'Use this for mounted shell routes that stay present behind dialogs without inventing extra filler content.',
    prompt: 'Render the Shell Route Empty View from Building Blocks using the canonical minimal mounted-shell backdrop with no extra demo content.',
    usedInShells: ['Add/Edit Record Shell', 'Add/Edit File Shell', 'Add/Edit BB Shell'],
    builtFromBbs: ['surfaces', 'spacing'],
    anatomy: ['Neutral mounted page surface', 'No extra helper copy', 'Dialog remains primary focus'],
  }),
}

export const BUILDING_BLOCK_OPTIONS = Object.entries(BUILDING_BLOCK_DETAILS_BY_ID).map(([value, detail]) => ({
  label: detail.title,
  value,
}))

export const BUILDING_BLOCK_SIZE_BY_ID = Object.freeze({
  fonts: 'full-row',
  'type-scale': 'full-row',
  'font-weights': 'lg',
  colors: 'full-row',
  surfaces: 'full-row',
  borders: 'lg',
  radius: 'lg',
  shadows: 'lg',
  spacing: 'full-row',
  'icon-sizing': 'lg',
  'formatting-rules': 'full-row',
  'motion-rules': 'full-row',
  'b10-logo': 'sm',
  'b10-button': 'md',
  'b10-icon-button': 'md',
  'main-menu-icon': 'md',
  'page-title-crumb': 'title-wide',
  'page-back-symbol': 'md',
  'file-shell-title-row': 'toolbar-wide',
  'record-shell-title-row': 'toolbar-wide',
  'main-menu-row': 'toolbar-wide',
  'main-menu-subgroup-row': 'toolbar-wide',
  'live-action-l1': 'live-link',
  'l2-toolbar': 'full-row',
  'l2-settings-menu': 'settings-menu',
  'widget-settings-menu': 'widget-settings',
  'dialog-shell-frame': 'full-row',
  'dialog-shell-title-row': 'toolbar-wide',
  'dialog-shell-footer': 'toolbar-wide',
  'toggle-row-icons': 'md',
  'shell-open-dialog-button': 'md',
  'shell-route-empty-view': 'toolbar-wide',
  'plus-icon': 'sm',
  'plus-with-label': 'md',
  'bb-tile-header': 'toolbar-wide',
  'eye-icon': 'sm',
  'edit-button': 'sm',
  'mini-scrollbar': 'md',
  'home-dashboard': 'full-row',
  'file-dashboard': 'full-row',
  'record-dashboard': 'full-row',
  'l3-box': 'stat-box',
  'file-toolbar': 'full-row',
  'record-hero-field-card': 'md',
  'record-context-panel': 'toolbar-wide',
  'record-feed-panel': 'toolbar-wide',
  'record-shell-launchpad': 'toolbar-wide',
  'file-filter-menu': 'settings-menu',
  'fork-selector-surface': 'live-link',
  'fork-branch-card': 'md',
})

export function getBuildingBlockTileSize(blockId) {
  return BUILDING_BLOCK_SIZE_BY_ID[String(blockId || '').trim()] || 'md'
}

const BUILDING_BLOCK_CATEGORY_BY_ID = Object.freeze({
  fonts: 'Basic Elements',
  'type-scale': 'Basic Elements',
  'font-weights': 'Basic Elements',
  colors: 'Basic Elements',
  surfaces: 'Basic Elements',
  borders: 'Basic Elements',
  radius: 'Basic Elements',
  shadows: 'Basic Elements',
  spacing: 'Basic Elements',
  'icon-sizing': 'Basic Elements',
  'formatting-rules': 'Basic Elements',
  'motion-rules': 'Basic Elements',
  'b10-logo': 'Basic Elements',
  'b10-button': 'Basic Elements',
  'b10-icon-button': 'Basic Elements',
  'main-menu-icon': 'Basic Elements',
  'page-title-crumb': 'Navigation Components',
  'page-back-symbol': 'Navigation Components',
  'file-shell-title-row': 'Navigation Components',
  'record-shell-title-row': 'Navigation Components',
  'main-menu-row': 'Navigation Components',
  'main-menu-subgroup-row': 'Navigation Components',
  'live-action-l1': 'Navigation Components',
  'l2-toolbar': 'Navigation Components',
  'l2-settings-menu': 'Navigation Components',
  'widget-settings-menu': 'Navigation Components',
  'toggle-row-icons': 'Navigation Components',
  'plus-icon': 'Dialog Components',
  'plus-with-label': 'Dialog Components',
  'bb-tile-header': 'Dialog Components',
  'dialog-shell-frame': 'Dialog Components',
  'dialog-shell-title-row': 'Dialog Components',
  'dialog-shell-footer': 'Dialog Components',
  'eye-icon': 'Dialog Components',
  'edit-button': 'Dialog Components',
  'mini-scrollbar': 'Dialog Components',
  'home-dashboard': 'File Components',
  'file-dashboard': 'File Components',
  'l3-box': 'File Components',
  'file-toolbar': 'File Components',
  'file-filter-menu': 'File Components',
  'record-dashboard': 'Record Components',
  'record-hero-field-card': 'Record Components',
  'record-context-panel': 'Record Components',
  'record-feed-panel': 'Record Components',
  'shell-open-dialog-button': 'Shell Components',
  'record-shell-launchpad': 'Shell Components',
  'fork-selector-surface': 'Shell Components',
  'fork-branch-card': 'Shell Components',
  'shell-route-empty-view': 'Shell Components',
})

export const DEFAULT_BUILDING_BLOCK_FILE_ROWS = Object.entries(BUILDING_BLOCK_DETAILS_BY_ID).map(([blockKey, detail], index) => ({
  id: `bb:${blockKey}`,
  Sort_Order: index + 1,
  Name: detail.title,
  Summary: detail.summary || '',
  Category: BUILDING_BLOCK_CATEGORY_BY_ID[blockKey] || 'Building Blocks',
  Status: detail.statusLabel || detail.status || '',
  Used_In: Array.isArray(detail.usedIn) ? detail.usedIn.join('\n') : '',
  Used_In_Shells: Array.isArray(detail.usedInShells) ? detail.usedInShells.join('\n') : '',
  Use_When: detail.summary || '',
  Avoid_When: '',
  Built_From_BBs: Array.isArray(detail.builtFromBbs) ? detail.builtFromBbs.join('\n') : '',
  Anatomy: Array.isArray(detail.anatomy) ? detail.anatomy.join('\n') : '',
  Required_Parts: Array.isArray(detail.anatomy) ? detail.anatomy.join('\n') : '',
  Source_Path: detail.source || '',
  Owner: 'BB Shell',
  Extraction_Status: detail.statusLabel || '',
  Reconstruction_Notes: Array.isArray(detail.reconstructionNotes) ? detail.reconstructionNotes.join('\n') : '',
  Prompt: detail.prompt || '',
  Variants: detail.status === 'canonical' ? 'Canonical Shared' : 'Extract Next',
}))

export function getBuildingBlockDetail(blockId) {
  return BUILDING_BLOCK_DETAILS_BY_ID[String(blockId || '').trim()] || null
}

function getDependencyMatchValues(blockKey, detail) {
  return new Set(
    [String(blockKey || '').trim(), detail?.id, detail?.title]
      .map((value) => String(value || '').trim())
      .filter(Boolean),
  )
}

export function getBuildingBlockGraphCounts(blockId) {
  const normalizedBlockId = String(blockId || '').trim()
  const detail = getBuildingBlockDetail(normalizedBlockId)
  if (!detail) {
    return { parentCount: 0, childCount: 0 }
  }

  const matchValues = getDependencyMatchValues(normalizedBlockId, detail)
  const childCount = Array.isArray(detail.builtFromBbs) ? detail.builtFromBbs.filter(Boolean).length : 0

  const parentCount = Object.entries(BUILDING_BLOCK_DETAILS_BY_ID).reduce((count, [, candidateDetail]) => {
    const dependencies = Array.isArray(candidateDetail?.builtFromBbs) ? candidateDetail.builtFromBbs : []
    return dependencies.some((dependency) => matchValues.has(String(dependency || '').trim()))
      ? count + 1
      : count
  }, 0)

  return { parentCount, childCount }
}

export function getBuildingBlockGraphLinks(blockId) {
  const normalizedBlockId = String(blockId || '').trim()
  const detail = getBuildingBlockDetail(normalizedBlockId)
  if (!detail) {
    return { parents: [], children: [] }
  }

  const matchValues = getDependencyMatchValues(normalizedBlockId, detail)
  const children = (Array.isArray(detail.builtFromBbs) ? detail.builtFromBbs : [])
    .map((dependency) => {
      const normalizedDependency = String(dependency || '').trim()
      const childDetail = getBuildingBlockDetail(normalizedDependency)
      if (!normalizedDependency) return null
      return {
        blockKey: normalizedDependency,
        title: childDetail?.title || normalizedDependency,
      }
    })
    .filter(Boolean)

  const parents = Object.entries(BUILDING_BLOCK_DETAILS_BY_ID)
    .filter(([, candidateDetail]) => {
      const dependencies = Array.isArray(candidateDetail?.builtFromBbs) ? candidateDetail.builtFromBbs : []
      return dependencies.some((dependency) => matchValues.has(String(dependency || '').trim()))
    })
    .map(([candidateKey, candidateDetail]) => ({
      blockKey: candidateKey,
      title: candidateDetail?.title || candidateKey,
    }))

  return { parents, children }
}
