function defineBuildingBlockDetail(detail) {
  return {
    builtFromBbs: detail.builtFromBbs || [],
    convergenceRule: detail.convergenceRule || [],
    usedInShells: detail.usedInShells || [],
    usedIn: detail.usedIn || [
      detail.source ? `Primary source: ${detail.source}` : 'Primary source not yet extracted.',
    ],
    anatomy: detail.anatomy || [
      'Preserve the same typography, spacing, icon treatment, and interaction state shown in Building Blocks.',
      'Prefer changing payload and labels before changing the underlying visual structure.',
    ],
    reconstructionNotes: detail.reconstructionNotes || [
      detail.summary,
      detail.nextStep,
    ].filter(Boolean),
    ...detail,
  }
}

export const BUILDING_BLOCK_DETAILS_BY_ID = {
  fonts: defineBuildingBlockDetail({
    id: 'cmp-foundation-fonts',
    title: 'Fonts',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/css/tokens.scss + src/utils/generalSettingsCatalog.js',
    nextStep: 'Use the General Settings token layer as the single source for font family selection and shell typography inheritance.',
    summary: 'Use this for the canonical font-family system that separates title and body roles.',
    prompt: 'Render the Fonts building block from BB Shell using the General Settings token source and the live title/body font pair.',
    anatomy: ['Title font sample', 'Body font sample', 'Explicit token labels'],
    usedInShells: ['BB Shell', 'Add/Edit BB Shell', 'Add/Edit Record Shell', 'Add/Edit File Shell', 'Record Shell', 'Fork Shell', 'Ingestion Shell'],
    convergenceRule: [
      '--ds-font-family-title -> --ds-font-title',
      '--ds-font-family-body -> --ds-font-body',
      'Shared shell surfaces should use ds font tokens directly instead of raw --font-title / --font-body',
    ],
  }),
  'type-scale': defineBuildingBlockDetail({
    id: 'cmp-foundation-type-scale',
    title: 'Type Scale',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/css/tokens.scss + src/utils/generalSettingsCatalog.js',
    nextStep: 'Use the General Settings token layer for shell type sizing instead of page-local size literals.',
    summary: 'Use this for the canonical type-size ladder across hero, body, and utility text.',
    prompt: 'Render the Type Scale building block from BB Shell using the live General Settings size tokens.',
    usedInShells: ['BB Shell', 'Add/Edit BB Shell', 'Add/Edit Record Shell', 'Add/Edit File Shell', 'Record Shell', 'Fork Shell', 'Ingestion Shell'],
    convergenceRule: [
      '--ds-font-size-xs-regular -> --ds-font-size-xs',
      '--ds-font-size-xs-medium -> --ds-font-size-xs',
      '--ds-font-size-sm-regular -> --ds-font-size-sm',
      '--ds-font-size-sm-medium -> --ds-font-size-sm',
      '--ds-font-size-base-regular -> --ds-font-size-base',
      '--ds-font-size-2xl -> --ds-font-size-page-title',
      '--ds-font-size-4xl -> --ds-font-size-hero',
    ],
  }),
  'font-weights': defineBuildingBlockDetail({
    id: 'cmp-foundation-font-weights',
    title: 'Font Weights',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/css/tokens.scss + src/utils/generalSettingsCatalog.js',
    nextStep: 'Use the General Settings token layer for weight changes instead of hardcoded numeric values in local components.',
    summary: 'Use this for the canonical weight ladder from light through bold.',
    prompt: 'Render the Font Weights building block from BB Shell using the live General Settings weight tokens.',
    usedInShells: ['BB Shell', 'Add/Edit BB Shell', 'Add/Edit Record Shell', 'Add/Edit File Shell', 'Record Shell', 'Fork Shell', 'Ingestion Shell'],
    convergenceRule: [
      'regular -> medium',
      'black -> bold',
      '400 -> medium',
      '700 -> bold',
      '800 -> bold',
      '900 -> bold',
    ],
  }),
  colors: defineBuildingBlockDetail({
    id: 'cmp-foundation-colors',
    title: 'Colors',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/css/tokens.scss + src/utils/generalSettingsCatalog.js',
    nextStep: 'Use the General Settings token layer for shell and component colors instead of drifting local hex values.',
    summary: 'Use this for the canonical text, brand, surface, and border color family.',
    prompt: 'Render the Colors building block from BB Shell using the live General Settings color tokens.',
    usedInShells: ['BB Shell', 'Add/Edit BB Shell', 'Add/Edit Record Shell', 'Add/Edit File Shell', 'Record Shell', 'Fork Shell', 'Ingestion Shell'],
    convergenceRule: [
      'Text Primary -> Brand Black',
      'Text Muted -> Brand Dark_Grey',
      'Border Soft -> Brand Light_Grey',
      'Surface Base -> Brand White',
      '--ds-color-text-header -> --ds-color-brand-black',
    ],
  }),
  surfaces: defineBuildingBlockDetail({
    id: 'cmp-foundation-surfaces',
    title: 'Surfaces',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/css/tokens.scss + src/utils/generalSettingsCatalog.js',
    nextStep: 'Use the General Settings token layer for surface backgrounds and overlay states.',
    summary: 'Use this for the canonical surface family that shells and cards sit on top of.',
    prompt: 'Render the Surfaces building block from BB Shell using the live General Settings surface tokens.',
    usedInShells: ['BB Shell', 'Add/Edit BB Shell', 'Add/Edit Record Shell', 'Add/Edit File Shell', 'Record Shell', 'Fork Shell', 'Ingestion Shell'],
    convergenceRule: [
      'base-88 -> overlay-light',
      'subtle-alt -> subtle',
      'overlay-72 -> overlay-light',
      'overlay-78 -> overlay-light',
      'overlay-84 -> overlay-light',
      'overlay-96 -> overlay-strong',
      'inverse -> base',
    ],
  }),
  borders: defineBuildingBlockDetail({
    id: 'cmp-foundation-borders',
    title: 'Borders',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/css/tokens.scss + src/utils/generalSettingsCatalog.js',
    nextStep: 'Use the General Settings token layer for shell and control border treatment.',
    summary: 'Use this for the canonical border language across cards, controls, and panels.',
    prompt: 'Render the Borders building block from BB Shell using the live General Settings border tokens.',
    usedInShells: ['BB Shell', 'Add/Edit BB Shell', 'Add/Edit Record Shell', 'Add/Edit File Shell', 'Record Shell', 'Fork Shell', 'Ingestion Shell'],
    convergenceRule: [
      'soft -> default',
      'soft-alt -> default',
      'strong -> default',
    ],
  }),
  radius: defineBuildingBlockDetail({
    id: 'cmp-foundation-radius',
    title: 'Radius',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/css/tokens.scss + src/utils/generalSettingsCatalog.js',
    nextStep: 'Use the General Settings token layer for corner treatments instead of per-page radius literals.',
    summary: 'Use this for the canonical corner-radius ladder from sharp shells to pill controls.',
    prompt: 'Render the Radius building block from BB Shell using the live General Settings radius tokens.',
    usedInShells: ['BB Shell', 'Add/Edit BB Shell', 'Add/Edit Record Shell', 'Add/Edit File Shell', 'Record Shell', 'Fork Shell', 'Ingestion Shell'],
    convergenceRule: [
      '16 -> 12',
      '18 -> 12',
      '20 -> 12',
      '24 -> 12',
    ],
  }),
  shadows: defineBuildingBlockDetail({
    id: 'cmp-foundation-shadows',
    title: 'Shadows',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/css/tokens.scss + src/utils/generalSettingsCatalog.js',
    nextStep: 'Use the General Settings token layer for elevation and focus shadows.',
    summary: 'Use this for the canonical shadow/elevation system across labels, cards, and controls.',
    prompt: 'Render the Shadows building block from BB Shell using the live General Settings shadow tokens.',
    usedInShells: ['BB Shell', 'Add/Edit BB Shell', 'Add/Edit Record Shell', 'Add/Edit File Shell', 'Record Shell', 'Fork Shell', 'Ingestion Shell'],
    convergenceRule: [
      '--ds-shadow-card-medium -> --ds-shadow-card-soft',
      'Card Soft + Card Medium -> Card',
    ],
  }),
  spacing: defineBuildingBlockDetail({
    id: 'cmp-foundation-spacing',
    title: 'Spacing',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/css/tokens.scss + src/utils/generalSettingsCatalog.js',
    nextStep: 'Use the General Settings token layer for spacing rhythm instead of arbitrary pixel values.',
    summary: 'Use this for the canonical spacing ladder that controls shell rhythm and component density.',
    prompt: 'Render the Spacing building block from BB Shell using the live General Settings spacing tokens.',
    usedInShells: ['BB Shell', 'Add/Edit BB Shell', 'Add/Edit Record Shell', 'Add/Edit File Shell', 'Record Shell', 'Fork Shell', 'Ingestion Shell'],
    convergenceRule: [
      '6 -> 8',
      '10 -> 8',
      '14 -> 12',
      '18 -> 16',
      '20 -> 16',
      '28 -> 24',
    ],
  }),
  'icon-sizing': defineBuildingBlockDetail({
    id: 'cmp-foundation-icon-sizing',
    title: 'Icon Sizing',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/css/tokens.scss + src/utils/generalSettingsCatalog.js',
    nextStep: 'Use the General Settings token layer for icon sizes across buttons, chips, and shell controls.',
    summary: 'Use this for the canonical icon-size ladder.',
    prompt: 'Render the Icon Sizing building block from BB Shell using the live General Settings icon size tokens.',
    usedInShells: ['BB Shell', 'Add/Edit BB Shell', 'Add/Edit Record Shell', 'Add/Edit File Shell', 'Record Shell', 'Fork Shell', 'Ingestion Shell'],
  }),
  'formatting-rules': defineBuildingBlockDetail({
    id: 'cmp-foundation-formatting-rules',
    title: 'Formatting Rules',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/utils/generalSettingsCatalog.js',
    nextStep: 'Promote number/date formatting into General Settings ownership instead of leaving formatting examples implied.',
    summary: 'Use this for the current number, currency, percent, date, and time formatting language.',
    prompt: 'Render the Formatting Rules building block from BB Shell using the canonical number/date formatting examples.',
    usedInShells: ['BB Shell', 'Add/Edit BB Shell', 'Add/Edit Record Shell', 'Add/Edit File Shell', 'Record Shell', 'Fork Shell', 'Ingestion Shell'],
  }),
  'motion-rules': defineBuildingBlockDetail({
    id: 'cmp-foundation-motion-rules',
    title: 'Motion Rules',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/utils/generalSettingsCatalog.js',
    nextStep: 'Keep shell motion purposeful and token-driven instead of page-local animation timing guesses.',
    summary: 'Use this for the current motion timing language across quick, standard, and emphasis interactions.',
    prompt: 'Render the Motion Rules building block from BB Shell using the canonical motion timing samples.',
    usedInShells: ['BB Shell', 'Add/Edit BB Shell', 'Add/Edit Record Shell', 'Add/Edit File Shell', 'Record Shell', 'Fork Shell', 'Ingestion Shell'],
  }),
  'home-dashboard': defineBuildingBlockDetail({
    id: 'cmp-home-dashboard',
    title: 'Home Dashboard',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/HomeDashboardHero.vue',
    nextStep: 'Reuse the shared hero directly and vary only the explicit home-dashboard payload.',
    summary: 'Use this for the live Home dashboard hero surface with overview count, top stats, workspace root, and signal chips.',
    prompt: 'Render the Home Dashboard component from Building Blocks by reusing the shared HomeDashboardHero component directly instead of recreating the hero layout locally.',
    usedIn: ['Home page hero surface', 'Building Blocks file component catalog'],
    usedInShells: ['BB Shell'],
    builtFromBbs: ['page-title', 'l3-box'],
    anatomy: ['Large page title treatment when used as a page header counterpart', 'Three stat blocks', 'Side panels for root path and active signal chips'],
  }),
  'page-title': defineBuildingBlockDetail({
    id: 'cmp-page-title',
    title: 'Page Title',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/PageTitleText.vue',
    nextStep: 'Reuse the shared PageTitleText directly and vary only explicit title payload.',
    summary: 'Use this for page headers that show the main page title.',
    prompt: 'Render the Page Title component from Building Blocks as the large standalone page title, using the same typography and spacing as the canonical component.',
    usedIn: ['Page-level shell headers', 'Any route-mounted page that needs large title treatment'],
    usedInShells: ['BB Shell', 'Add/Edit BB Shell', 'Add/Edit Record Shell', 'Add/Edit File Shell', 'Record Shell', 'Fork Shell', 'Ingestion Shell'],
    builtFromBbs: ['fonts', 'type-scale', 'font-weights', 'colors', 'spacing'],
    anatomy: ['Large title row', 'Title font with tight tracking'],
  }),
  'record-title': defineBuildingBlockDetail({
    id: 'cmp-record-title',
    title: 'Record Title',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/RecordTitle.vue',
    nextStep: 'Reuse the shared RecordTitle directly anywhere record and hero surfaces need the larger hero-title treatment.',
    summary: 'Use this for record and file hero titles that should render at hero size.',
    prompt: 'Render the Record Title from Building Blocks using the page-title family but sized to the hero title token.',
    usedInShells: ['BB Shell'],
    builtFromBbs: ['page-title', 'colors', 'spacing'],
    anatomy: ['Large hero title row', 'Title font with tight tracking'],
  }),
  'page-back-symbol': defineBuildingBlockDetail({
    id: 'cmp-page-back-symbol',
    title: 'Page Back Symbol',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/PageBackSymbol.vue',
    nextStep: 'Reuse the shared PageBackSymbol directly and vary only explicit icon/label payload.',
    summary: 'Use this for compact back navigation inside shell headers and detail surfaces.',
    prompt: 'Render the Page Back Symbol from Building Blocks exactly, using the same single wrapper around the west icon and Back label.',
    usedIn: ['Shell header left cluster', 'Pages with explicit back navigation'],
    usedInShells: ['BB Shell', 'Add/Edit BB Shell', 'Add/Edit Record Shell', 'Add/Edit File Shell', 'Record Shell', 'Fork Shell', 'Ingestion Shell'],
    builtFromBbs: ['west-icon', 'page-back-label', 'spacing', 'borders', 'radius', 'surfaces'],
    anatomy: ['Left-pointing west icon', 'Back label', 'Shared wrapper around both'],
  }),
  'west-icon': defineBuildingBlockDetail({
    id: 'cmp-west-icon',
    title: 'West Icon',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/WestIcon.vue',
    nextStep: 'Reuse the shared WestIcon directly anywhere the same bare back glyph is needed.',
    summary: 'Use this for the stand-alone back glyph with no button wrapper or hover treatment.',
    prompt: 'Render the West Icon from Building Blocks as the bare west glyph only, with no button behavior or wrapper.',
    usedInShells: ['BB Shell', 'Add/Edit BB Shell', 'Add/Edit Record Shell', 'Add/Edit File Shell', 'Record Shell', 'Fork Shell', 'Ingestion Shell'],
    builtFromBbs: ['colors', 'icon-sizing'],
    anatomy: ['Bare west glyph', 'No wrapper', 'No hover interaction'],
  }),
  'page-back-label': defineBuildingBlockDetail({
    id: 'cmp-page-back-label',
    title: 'Page Back Label',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/PageBackLabel.vue',
    nextStep: 'Reuse the shared PageBackLabel directly anywhere the same back-navigation text treatment is needed.',
    summary: 'Use this for the compact Back label paired with the west icon.',
    prompt: 'Render the Page Back Label from Building Blocks using the same title-font Back text treatment as the canonical page-back control.',
    usedInShells: ['BB Shell', 'Add/Edit BB Shell', 'Add/Edit Record Shell', 'Add/Edit File Shell', 'Record Shell', 'Fork Shell', 'Ingestion Shell'],
    builtFromBbs: ['fonts', 'font-weights', 'colors'],
    anatomy: ['Back label text', 'Title font treatment', 'Compact inline sizing'],
  }),
  'button-label': defineBuildingBlockDetail({
    id: 'cmp-button-label',
    title: 'Button Label',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/ButtonLabel.vue',
    nextStep: 'Reuse the shared ButtonLabel anywhere the same B10 button text treatment is needed.',
    summary: 'Use this for canonical B10 button text instead of recreating button typography locally.',
    prompt: 'Render the Button Label from Building Blocks using the same shared B10 button typography treatment.',
    usedInShells: ['BB Shell', 'Add/Edit BB Shell', 'Add/Edit Record Shell', 'Add/Edit File Shell', 'Record Shell', 'Fork Shell', 'Ingestion Shell'],
    builtFromBbs: ['fonts', 'font-weights', 'colors', 'spacing'],
    anatomy: ['Button label text', 'B10 type treatment', 'Inline action sizing'],
  }),
  'b10-logo': defineBuildingBlockDetail({
    id: 'cmp-b10-logo',
    title: 'B10 Logo',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/B10Logo.vue',
    nextStep: 'Reuse the shared B10Logo directly anywhere the live animated brand treatment is needed.',
    summary: 'Use this for compact brand badges or temporary logo placeholders.',
    prompt: 'Render the B10 Logo from Building Blocks using the shared animated brand logo component and its fallback text behavior.',
    usedInShells: ['BB Shell', 'Add/Edit BB Shell', 'Add/Edit Record Shell', 'Add/Edit File Shell', 'Record Shell', 'Fork Shell', 'Ingestion Shell'],
    builtFromBbs: ['fonts', 'colors', 'radius', 'spacing'],
  }),
  'plus-icon': defineBuildingBlockDetail({
    id: 'cmp-plus-icon',
    title: 'Plus Icon',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/PlusIconChip.vue',
    nextStep: 'Reuse the shared PlusIconChip directly and vary only explicit approved size variants.',
    summary: 'Use this for isolated add actions where only the icon should show.',
    prompt: 'Render the Plus Icon component from Building Blocks exactly, using the same electric-blue circular button with white plus icon.',
    usedInShells: ['BB Shell', 'Add/Edit BB Shell', 'Add/Edit Record Shell', 'Add/Edit File Shell'],
    builtFromBbs: ['colors', 'radius', 'icon-sizing'],
  }),
  'plus-with-label': defineBuildingBlockDetail({
    id: 'cmp-plus-with-label',
    title: 'Plus With Label',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/PlusWithLabelButton.vue',
    nextStep: 'Reuse the shared PlusWithLabelButton directly and vary only explicit label payload.',
    summary: 'Use this for add actions that need icon plus text in one control.',
    prompt: 'Render the Plus With Label component from Building Blocks exactly, using the same electric-blue button, white plus icon, and title-font label treatment.',
    usedInShells: ['BB Shell', 'Add/Edit BB Shell', 'Add/Edit Record Shell', 'Add/Edit File Shell', 'File Shell', 'Record Shell'],
    builtFromBbs: ['plus-icon', 'fonts', 'font-weights', 'colors', 'spacing'],
  }),
  'bb-tile-header': defineBuildingBlockDetail({
    id: 'cmp-bb-tile-header',
    title: 'BB Tile Header',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/BuildingBlockTileHeader.vue',
    nextStep: 'Reuse the shared BuildingBlockTileHeader directly across BB tiles and related catalog surfaces.',
    summary: 'Use this for the top row of BB tiles with title, collapse arrow, copy action, and view action.',
    prompt: 'Render the BB Tile Header from Building Blocks using the same cool title type, collapse arrow, copy action, and eye action aligned in one compact top row.',
    usedIn: ['BB Shell tile top row', 'Building Blocks tile top row'],
    usedInShells: ['BB Shell', 'Add/Edit BB Shell'],
    builtFromBbs: ['eye-icon', 'font-weights', 'colors', 'spacing'],
    anatomy: ['Strong title-style text on the left', 'Collapse / expand arrow inline with the title', 'Copy icon action', 'Eye icon action'],
  }),
  'value-chip': defineBuildingBlockDetail({
    id: 'cmp-value-chip',
    title: 'Value Chip',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/ValueChip.vue',
    nextStep: 'Reuse the shared ValueChip directly and vary only explicit label/tone payload.',
    summary: 'Use this for the compact black chip that shows the active selected value.',
    prompt: 'Render the Value Chip from Building Blocks using the same black chip, white title text, and tight inline padding as the live shell selector.',
    usedInShells: ['Record Shell', 'Fork Shell'],
    builtFromBbs: ['value-chip-surface', 'value-chip-label'],
    anatomy: ['Black chip surface', 'White value text', 'Tight horizontal padding'],
  }),
  'value-chip-surface': defineBuildingBlockDetail({
    id: 'cmp-value-chip-surface',
    title: 'Value Chip Surface',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/ValueChipSurface.vue',
    nextStep: 'Reuse the shared ValueChipSurface directly anywhere the black outlined chip container is needed.',
    summary: 'Use this for the compact black chip surface behind selected values.',
    prompt: 'Render the Value Chip Surface from Building Blocks using the same black chip container, outline, radius, and padding as the canonical selector chip.',
    usedInShells: ['Record Shell', 'Fork Shell'],
    builtFromBbs: ['colors', 'borders', 'radius', 'spacing'],
    anatomy: ['Black chip surface', 'White outline', 'Compact horizontal padding'],
  }),
  'value-chip-label': defineBuildingBlockDetail({
    id: 'cmp-value-chip-label',
    title: 'Value Chip Label',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/ValueChipLabel.vue',
    nextStep: 'Reuse the shared ValueChipLabel directly anywhere the selected-value chip text treatment is needed.',
    summary: 'Use this for the white lowercase value text inside selected chips.',
    prompt: 'Render the Value Chip Label from Building Blocks using the same white lowercase title-font treatment as the canonical selector chip.',
    usedInShells: ['Record Shell', 'Fork Shell'],
    builtFromBbs: ['fonts', 'type-scale', 'font-weights', 'colors'],
    anatomy: ['White label text', 'Title font treatment', 'Lowercase value copy'],
  }),
  'dropdown-chevron': defineBuildingBlockDetail({
    id: 'cmp-dropdown-chevron',
    title: 'Dropdown Chevron',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/DropdownChevron.vue',
    nextStep: 'Reuse the shared DropdownChevron directly anywhere shell or chip selectors need the same affordance.',
    summary: 'Use this for the dropdown chevron attached to selector and chip surfaces.',
    prompt: 'Render the Dropdown Chevron from Building Blocks using the same downward chevron treatment and offset used in the live shell selector.',
    usedInShells: ['Record Shell', 'Fork Shell'],
    builtFromBbs: ['colors', 'icon-sizing', 'spacing'],
    anatomy: ['Downward chevron icon', 'Selector-edge placement', 'Compact hover target'],
  }),
  'live-action-l1': defineBuildingBlockDetail({
    id: 'cmp-live-action-l1',
    title: 'Live Action L1',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/LiveActionL1.vue',
    nextStep: 'Reuse the shared LiveActionL1 directly and vary only explicit options, selection, and tone payload.',
    summary: 'Use this for shell-level live source selectors that sit in the top center and switch the active L1 context.',
    prompt: 'Render the Live Action L1 control from Building Blocks exactly, using the same black value chip and chevron treatment as the canonical shell selector.',
    usedInShells: ['Record Shell', 'Fork Shell'],
    builtFromBbs: ['value-chip', 'dropdown-chevron', 'fonts', 'font-weights', 'colors', 'borders', 'radius', 'spacing'],
  }),
  'shell-title-row': defineBuildingBlockDetail({
    id: 'cmp-shell-title-row',
    title: 'Shell Title Row',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/FileShellTitleRow.vue',
    nextStep: 'Reuse the shared Shell Title Row directly and vary only explicit title and selector payload.',
    summary: 'Use this for shell header rows that combine page title, back symbol, and live selector in one lane.',
    prompt: 'Render the Shell Title Row from Building Blocks using the canonical composition of page title, page back symbol, and live action selector.',
    usedInShells: ['File Shell', 'Record Shell', 'BB Shell'],
    builtFromBbs: ['page-back-symbol', 'page-title', 'live-action-l1', 'colors', 'spacing'],
    anatomy: ['Page title treatment', 'Back symbol', 'Live selector'],
  }),
  'b10-button': defineBuildingBlockDetail({
    id: 'cmp-b10-button',
    title: 'B10 Button',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/buttons/B10Button.vue',
    nextStep: 'Reuse this component directly and vary only payload props such as label, icon, and variant.',
    summary: 'Use this for canonical B10 action buttons composed from the shared button surface and button label children.',
    prompt: 'Render the B10 Button component from Building Blocks using the shared button surface and button label children instead of local button styles.',
    usedInShells: ['BB Shell', 'Add/Edit BB Shell', 'Add/Edit Record Shell', 'Add/Edit File Shell', 'Record Shell', 'Fork Shell', 'Ingestion Shell'],
    builtFromBbs: ['value-chip-surface', 'button-label', 'colors', 'radius', 'spacing', 'icon-sizing'],
  }),
  'b10-icon-button': defineBuildingBlockDetail({
    id: 'cmp-b10-icon-button',
    title: 'B10 Icon Button',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/buttons/B10IconButton.vue',
    nextStep: 'Reuse this component directly and vary only icon and variant props.',
    summary: 'Use this for canonical icon-only actions that should come from the B10 button system.',
    prompt: 'Render the B10 Icon Button component from Building Blocks using the shared B10IconButton component and its existing variants.',
    usedInShells: ['BB Shell', 'Add/Edit BB Shell', 'Add/Edit Record Shell', 'Add/Edit File Shell', 'Record Shell', 'Fork Shell', 'Ingestion Shell'],
    builtFromBbs: ['colors', 'radius', 'icon-sizing', 'spacing'],
  }),
  'view-mode-toggle': defineBuildingBlockDetail({
    id: 'cmp-view-mode-toggle',
    title: 'View Mode Toggle',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/ViewModeToggle.vue',
    nextStep: 'Reuse the shared ViewModeToggle directly anywhere shell surfaces need the same row/grid or card/table mode switching.',
    summary: 'Use this for compact mode switching across toolbars and shell control lanes.',
    prompt: 'Render the View Mode Toggle from Building Blocks using the shared toggle component and the same compact icon-button layout as the canonical toolbar controls.',
    usedInShells: ['BB Shell', 'File Shell', 'Record Shell'],
    builtFromBbs: ['colors', 'surfaces', 'borders', 'radius', 'spacing', 'icon-sizing'],
  }),
  'filter-list-icon': defineBuildingBlockDetail({
    id: 'cmp-filter-list-icon',
    title: 'Filter List Icon',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/FilterListIcon.vue',
    nextStep: 'Reuse the shared filter trigger directly anywhere the same compact toolbar filter icon is needed.',
    summary: 'Use this for the canonical three-line filter trigger used in BB Shell and file toolbar controls.',
    prompt: 'Render the Filter List Icon from Building Blocks using the shared filter_list trigger and the same muted toolbar treatment as the BB Shell filter control.',
    usedInShells: ['BB Shell', 'File Shell'],
    builtFromBbs: ['colors', 'spacing', 'icon-sizing'],
  }),
  'search-bar-input': defineBuildingBlockDetail({
    id: 'cmp-search-bar-input',
    title: 'Search Bar Input',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/SearchBarInput.vue',
    nextStep: 'Reuse the shared search input directly anywhere shell and file surfaces need the same compact search control.',
    summary: 'Use this for the canonical toolbar search input with leading search icon.',
    prompt: 'Render the Search Bar Input from Building Blocks using the shared search field and the canonical control surface tokens.',
    usedInShells: ['BB Shell', 'File Shell'],
    builtFromBbs: ['colors', 'surfaces', 'borders', 'radius', 'spacing', 'icon-sizing'],
  }),
  'bb-code-input': defineBuildingBlockDetail({
    id: 'cmp-bb-code-input',
    title: 'BB Code Input',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/BbCodeInput.vue',
    nextStep: 'Reuse the shared BB code input directly anywhere the Add/Edit BB flow needs exact bb:code entry.',
    summary: 'Use this for the compact centered code-entry input without a search icon.',
    prompt: 'Render the BB Code Input from Building Blocks using the compact centered bb:code entry field with no leading icon.',
    usedInShells: ['BB Shell', 'Add/Edit BB Shell'],
    builtFromBbs: ['colors', 'surfaces', 'borders', 'radius', 'spacing'],
  }),
  'settings-checkbox': defineBuildingBlockDetail({
    id: 'cmp-settings-checkbox',
    title: 'Settings Checkbox',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/SettingsCheckbox.vue',
    nextStep: 'Reuse the shared settings checkbox directly anywhere settings menus need the same black/white checkbox treatment.',
    summary: 'Use this for canonical settings-menu checkboxes in light and dark menu surfaces.',
    prompt: 'Render the Settings Checkbox from Building Blocks using the shared checkbox component and the same black/white menu checkbox treatment in both light and dark variants.',
    usedInShells: ['BB Shell', 'File Shell', 'Record Shell'],
    builtFromBbs: ['colors', 'surfaces', 'borders', 'spacing'],
  }),
  'main-menu-icon': defineBuildingBlockDetail({
    id: 'cmp-main-menu-icon',
    title: 'Main Menu Icon',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/buttons/MainMenuIconButton.vue',
    nextStep: 'Reuse the shared MainMenuIconButton directly in header and catalog surfaces.',
    summary: 'Use this for the compact menu trigger in the top-left shell header.',
    prompt: 'Render the Main Menu Icon from Building Blocks using the same flat round menu button treatment as the shell header drawer trigger.',
    usedInShells: ['Main Layout'],
    builtFromBbs: ['colors', 'icon-sizing'],
  }),
  'main-menu-row-icon': defineBuildingBlockDetail({
    id: 'cmp-main-menu-row-icon',
    title: 'Main Menu Row Icon',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/MainMenuRowIcon.vue',
    nextStep: 'Reuse the shared MainMenuRowIcon directly anywhere a left-drawer nav row needs the same icon treatment.',
    summary: 'Use this for standard left-drawer row icons like Files, BB Shell, and Record Shell.',
    prompt: 'Render the Main Menu Row Icon from Building Blocks using the same left-drawer row icon sizing and placement as the canonical nav row.',
    usedInShells: ['Main Layout'],
    builtFromBbs: ['colors', 'icon-sizing', 'spacing'],
  }),
  'main-menu-row-label': defineBuildingBlockDetail({
    id: 'cmp-main-menu-row-label',
    title: 'Main Menu Row Label',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/MainMenuRowLabel.vue',
    nextStep: 'Reuse the shared MainMenuRowLabel directly anywhere a left-drawer nav row needs the same label treatment.',
    summary: 'Use this for standard left-drawer row labels like Files, BB Shell, and Record Shell.',
    prompt: 'Render the Main Menu Row Label from Building Blocks using the same light-weight white drawer label treatment as the canonical nav row.',
    usedInShells: ['Main Layout'],
    builtFromBbs: ['fonts', 'font-weights', 'colors'],
  }),
  'l3-box': defineBuildingBlockDetail({
    id: 'cmp-l3-box',
    title: 'L3 Box',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/L3Box.vue',
    nextStep: 'Reuse the shared L3Box directly and vary only explicit label, value, caption, and tone payload.',
    summary: 'Use this for the standalone L3 stat card that appears inside the shell dashboard metrics strip.',
    prompt: 'Render the L3 Box from Building Blocks exactly, using the same compact dashboard stat-card treatment with label, large value, and caption.',
    usedInShells: ['BB Shell', 'File Shell', 'Record Shell'],
    builtFromBbs: ['type-scale', 'font-weights', 'colors', 'surfaces', 'borders', 'radius', 'spacing'],
  }),
  'file-toolbar': defineBuildingBlockDetail({
    id: 'cmp-file-toolbar',
    title: 'File Toolbar',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/FilePageToolbar.vue',
    nextStep: 'Reuse the shared toolbar directly and vary only its explicit props and payload.',
    summary: 'Use this for the top toolbar inside file pages with add, search, and view controls.',
    prompt: 'Render the File Toolbar component from Building Blocks using the real FilePageToolbar component, keeping its existing add, search, and view-toggle layout.',
    usedInShells: ['BB Shell', 'File Shell'],
    builtFromBbs: ['plus-with-label', 'filter-list-icon', 'search-bar-input', 'view-mode-toggle', 'colors', 'surfaces', 'borders', 'radius', 'spacing'],
  }),
  'record-hero': defineBuildingBlockDetail({
    id: 'cmp-record-hero',
    title: 'Record Hero',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/RecordHero.vue',
    nextStep: 'Reuse this as the canonical record hero anywhere record hero surfaces are needed.',
    summary: 'Use this for the canonical record hero with portrait, record title, settings, fields box, summary box, and record feed.',
    prompt: 'Render the Record Hero from Building Blocks using the shared hero surface, 3-column overlay, record title, fields box, summary box, and record feed.',
    usedInShells: ['BB Shell'],
    builtFromBbs: ['hero-surface', 'hero-3col-overlay', 'record-title', 'l2-settings-menu', 'record-fields-box', 'record-summary-box', 'record-feed-panel'],
    anatomy: ['Portrait lane', 'Record title + settings row', 'Fields box', 'Summary box', 'Record feed'],
  }),
  'hero-surface': defineBuildingBlockDetail({
    id: 'cmp-hero-surface',
    title: 'Hero Surface',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/HeroSurface.vue',
    nextStep: 'Use this as the large background and shadow owner for hero sandbox experiments.',
    summary: 'Use this for the large hero background, blur, radius, and shadow frame.',
    usedInShells: ['BB Shell'],
    builtFromBbs: ['surfaces', 'radius', 'shadows'],
  }),
  'hero-3col-overlay': defineBuildingBlockDetail({
    id: 'cmp-hero-overlay',
    title: 'Hero 3Col Overlay',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/Hero3ColOverlay.vue',
    nextStep: 'Use this as the transparent three-column overlay owner for hero sandbox experiments.',
    summary: 'Use this for the transparent three-box overlay that sits on top of the hero surface.',
    usedInShells: ['BB Shell'],
    builtFromBbs: ['surfaces', 'radius', 'spacing'],
  }),
  'hero-2col-overlay': defineBuildingBlockDetail({
    id: 'cmp-hero-2col-overlay',
    title: 'Hero 2Col Overlay',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/Hero2ColOverlay.vue',
    nextStep: 'Use this as the transparent two-column overlay owner for file hero sandbox experiments.',
    summary: 'Use this for the transparent two-box overlay with the right column smaller.',
    usedInShells: ['BB Shell'],
    builtFromBbs: ['surfaces', 'radius', 'spacing'],
  }),
  'record-hero-field-card': defineBuildingBlockDetail({
    id: 'cmp-record-hero-field-card',
    title: 'Record Hero Field Card',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/RecordHeroFieldCard.vue',
    nextStep: 'Reuse the shared RecordHeroFieldCard directly and vary only explicit label, description, value, and status-icon payload.',
    summary: 'Use this for the record-shell hero cards that show a label, descriptor, value, and optional status icon.',
    prompt: 'Render the Record Hero Field Card from Building Blocks using the shared record hero field card and the same label, descriptor, value, and status-icon treatment as Record Shell.',
    usedInShells: ['Record Shell'],
    builtFromBbs: ['record-field-label', 'record-field-description', 'record-field-value', 'record-field-status-icon'],
    anatomy: ['Field label', 'Field description', 'Primary value', 'Optional status icon'],
  }),
  'record-field-label': defineBuildingBlockDetail({
    id: 'cmp-record-field-label',
    title: 'Record Field Label',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/RecordFieldLabel.vue',
    nextStep: 'Reuse the shared RecordFieldLabel directly anywhere the same compact hero-card field tag is needed.',
    summary: 'Use this for the compact black field label in record hero cards.',
    prompt: 'Render the Record Field Label from Building Blocks using the shared compact black label used at the top-left of record hero cards.',
    usedInShells: ['BB Shell', 'Record Shell'],
    builtFromBbs: ['fonts', 'type-scale', 'font-weights', 'colors', 'surfaces', 'borders', 'radius', 'spacing'],
    anatomy: ['Compact black surface', 'White title-style text', 'Field tag label'],
  }),
  'record-field-description': defineBuildingBlockDetail({
    id: 'cmp-record-field-description',
    title: 'Record Field Description',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/RecordFieldDescription.vue',
    nextStep: 'Reuse the shared RecordFieldDescription directly anywhere the same muted inline descriptor is needed.',
    summary: 'Use this for the muted descriptor that appears at the top-right of record hero cards.',
    prompt: 'Render the Record Field Description from Building Blocks using the shared muted descriptor text used in record hero cards.',
    usedInShells: ['BB Shell', 'Record Shell'],
    builtFromBbs: ['fonts', 'type-scale', 'font-weights', 'colors', 'spacing'],
    anatomy: ['Muted descriptor text', 'Inline right-side placement', 'Compact helper copy'],
  }),
  'record-field-value': defineBuildingBlockDetail({
    id: 'cmp-record-field-value',
    title: 'Record Field Value',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/RecordFieldValue.vue',
    nextStep: 'Reuse the shared RecordFieldValue directly anywhere the same soft value pill is needed in record hero cards.',
    summary: 'Use this for the lower value block in record hero cards.',
    prompt: 'Render the Record Field Value from Building Blocks using the shared lower value block used in record hero cards.',
    usedInShells: ['BB Shell', 'Record Shell'],
    builtFromBbs: ['fonts', 'type-scale', 'font-weights', 'colors', 'surfaces', 'radius', 'spacing'],
    anatomy: ['Soft value surface', 'Muted value text', 'Compact lower-row block'],
  }),
  'record-fields-box': defineBuildingBlockDetail({
    id: 'cmp-record-fields-box',
    title: 'Record Fields Box',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/RecordFieldsBox.vue',
    nextStep: 'Use this as the selected-fields container surface anywhere record hero fields need a shared framed box.',
    summary: 'Use this for the outer container that holds selected record hero field cards.',
    usedInShells: ['BB Shell'],
    builtFromBbs: ['surfaces', 'radius', 'spacing', 'record-hero-field-card'],
    anatomy: ['Outer container surface', 'Shared padding and radius', 'Hosts record hero field cards as slotted children'],
  }),
  'record-summary-box': defineBuildingBlockDetail({
    id: 'cmp-record-summary-box',
    title: 'Record Summary Box',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/RecordSummaryBox.vue',
    nextStep: 'Use this as the summary container surface anywhere record hero summaries need a shared framed box.',
    summary: 'Use this for the outer container that holds record hero summary content.',
    usedInShells: ['BB Shell'],
    builtFromBbs: ['surfaces', 'radius', 'spacing'],
    anatomy: ['Outer container surface', 'Shared padding and radius', 'Hosts summary content as slotted children'],
  }),
  'file-hero': defineBuildingBlockDetail({
    id: 'cmp-file-hero',
    title: 'File Hero',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/FileHero.vue',
    nextStep: 'Reuse this as the canonical file hero anywhere file hero surfaces are needed.',
    summary: 'Use this for the canonical file hero with record title, summary copy, a 2 x 2 l3-box grid, and derived file health.',
    usedInShells: ['BB Shell'],
    builtFromBbs: ['hero-surface', 'hero-2col-overlay', 'record-title', 'l3-box'],
    anatomy: ['Record title', 'Summary copy', '2 x 2 l3-box grid', 'Derived file-health box'],
  }),
  'record-field-status-icon': defineBuildingBlockDetail({
    id: 'cmp-record-field-status-icon',
    title: 'Record Field Status Icon',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/RecordFieldStatusIcon.vue',
    nextStep: 'Reuse the shared RecordFieldStatusIcon directly anywhere the same verified hero-card status mark is needed.',
    summary: 'Use this for the small blue status icon that appears in record hero field cards.',
    prompt: 'Render the Record Field Status Icon from Building Blocks using the shared task_alt status mark from the record hero card family.',
    usedInShells: ['BB Shell', 'Record Shell'],
    builtFromBbs: ['colors', 'icon-sizing'],
    anatomy: ['Verified status glyph', 'Blue icon color', 'Compact 20px lane'],
  }),
  'record-context-panel': defineBuildingBlockDetail({
    id: 'cmp-record-context-panel',
    title: 'Record Context Panel',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/RecordContextPanel.vue',
    nextStep: 'Reuse the shared RecordContextPanel directly and vary only explicit notes, documents, tab state, and singular-label payload.',
    summary: 'Use this for the tabbed record context surface that shows latest notes and related artifacts.',
    prompt: 'Render the Record Context Panel from Building Blocks using the same tabbed side-panel treatment from Record Shell, including context tabs, list rows, and empty states.',
    usedInShells: ['Record Shell'],
    builtFromBbs: ['value-chip-surface', 'record-feed-tab-label', 'button-label', 'main-menu-row-label', 'record-field-description', 'spacing'],
    anatomy: ['Context tabs', 'Context list rows', 'Context meta line', 'Empty state copy'],
  }),
  'record-feed-panel': defineBuildingBlockDetail({
    id: 'cmp-record-feed-panel',
    title: 'Record Feed Panel',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/RecordFeedPanel.vue',
    nextStep: 'Reuse the shared RecordFeedPanel directly and vary only explicit feed items, tab state, and open-log behavior.',
    summary: 'Use this for the right-side record feed surface with feed tabs, entries, and open-log actions.',
    prompt: 'Render the Record Feed Panel from Building Blocks using the same Record Shell feed panel with header, tab row, feed entries, and open-log action.',
    usedInShells: ['Record Shell'],
    builtFromBbs: ['record-feed-label', 'record-feed-tab-label', 'record-feed-time', 'record-feed-entry-title', 'record-feed-empty', 'record-feed-entry-surface', 'value-chip-surface', 'eye-icon'],
    anatomy: ['Feed header', 'Feed tabs', 'Feed entry row', 'Open-log action'],
  }),
  'record-feed-tab-label': defineBuildingBlockDetail({
    id: 'cmp-record-feed-tab-label',
    title: 'Record Feed Tab Label',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/RecordFeedTabLabel.vue',
    nextStep: 'Reuse the shared RecordFeedTabLabel directly anywhere the same uppercase feed-tab text treatment is needed.',
    summary: 'Use this for the compact uppercase label inside record feed tabs.',
    prompt: 'Render the Record Feed Tab Label from Building Blocks using the shared compact uppercase feed-tab label used in the record feed panel.',
    usedInShells: ['BB Shell', 'Record Shell'],
    builtFromBbs: ['fonts', 'type-scale', 'font-weights', 'colors'],
    anatomy: ['Uppercase tab text', 'Compact feed-tab label'],
  }),
  'record-feed-label': defineBuildingBlockDetail({
    id: 'cmp-record-feed-label',
    title: 'Record Feed Label',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/RecordFeedLabel.vue',
    nextStep: 'Reuse the shared RecordFeedLabel directly anywhere the same feed-panel header treatment is needed.',
    summary: 'Use this for the main Record Feed heading at the top of feed panels.',
    prompt: 'Render the Record Feed Label from Building Blocks using the shared white title treatment used in the record feed panel header.',
    usedInShells: ['BB Shell', 'Record Shell'],
    builtFromBbs: ['fonts', 'type-scale', 'font-weights', 'colors'],
    anatomy: ['White title text', 'Compact header line', 'Feed section heading'],
  }),
  'record-feed-time': defineBuildingBlockDetail({
    id: 'cmp-record-feed-time',
    title: 'Record Feed Time',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/RecordFeedTime.vue',
    nextStep: 'Reuse the shared RecordFeedTime directly anywhere the same muted feed meta text is needed.',
    summary: 'Use this for the muted time/meta text that sits at the top of a feed entry.',
    prompt: 'Render the Record Feed Time from Building Blocks using the shared muted feed meta text used in record feed entries.',
    usedInShells: ['BB Shell', 'Record Shell'],
    builtFromBbs: ['fonts', 'type-scale', 'colors'],
    anatomy: ['Muted time text', 'Small meta line', 'Feed entry timestamp'],
  }),
  'record-feed-entry-title': defineBuildingBlockDetail({
    id: 'cmp-record-feed-entry-title',
    title: 'Record Feed Entry Title',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/RecordFeedEntryTitle.vue',
    nextStep: 'Reuse the shared RecordFeedEntryTitle directly anywhere the same white feed-row title is needed.',
    summary: 'Use this for the main entry title text inside record feed rows.',
    prompt: 'Render the Record Feed Entry Title from Building Blocks using the shared white feed-entry title treatment.',
    usedInShells: ['BB Shell', 'Record Shell'],
    builtFromBbs: ['fonts', 'type-scale', 'font-weights', 'colors'],
    anatomy: ['White title text', 'Entry title line', 'Feed row heading'],
  }),
  'record-feed-empty': defineBuildingBlockDetail({
    id: 'cmp-record-feed-empty',
    title: 'Record Feed Empty',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/RecordFeedEmpty.vue',
    nextStep: 'Reuse the shared RecordFeedEmpty directly anywhere the same muted empty-state copy is needed in feed panels.',
    summary: 'Use this for the muted empty-state copy shown when no feed items exist.',
    prompt: 'Render the Record Feed Empty text from Building Blocks using the shared muted empty-state copy used in the record feed panel.',
    usedInShells: ['BB Shell', 'Record Shell'],
    builtFromBbs: ['fonts', 'type-scale', 'colors'],
    anatomy: ['Muted empty text', 'Panel empty state copy'],
  }),
  'record-feed-entry-surface': defineBuildingBlockDetail({
    id: 'cmp-record-feed-entry-surface',
    title: 'Record Feed Entry Surface',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/RecordFeedEntrySurface.vue',
    nextStep: 'Reuse the shared RecordFeedEntrySurface directly anywhere the same dark feed-entry surface is needed.',
    summary: 'Use this for the dark translucent row surface used by record feed entries.',
    prompt: 'Render the Record Feed Entry Surface from Building Blocks using the shared dark translucent feed-entry box.',
    usedInShells: ['BB Shell', 'Record Shell'],
    builtFromBbs: ['surfaces', 'borders', 'radius', 'spacing'],
    anatomy: ['Dark translucent row', 'Mini radius edge', 'Compact padded entry surface'],
  }),
  'l2-toolbar': defineBuildingBlockDetail({
    id: 'cmp-l2-toolbar',
    title: 'L2 Toolbar',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/ShellSectionToolbar.vue',
    nextStep: 'Reuse the shared section toolbar directly and vary only section items and selected payload.',
    summary: 'Use this for section switching across General, KDB, System, and similar level-2 groupings.',
    prompt: 'Render the L2 Toolbar component from Building Blocks using the real ShellSectionToolbar component with the same compact section-chip treatment.',
    usedInShells: ['BB Shell', 'File Shell', 'Record Shell'],
    builtFromBbs: ['view-mode-toggle', 'colors', 'surfaces', 'borders', 'radius', 'spacing'],
  }),
  'l2-settings-menu': defineBuildingBlockDetail({
    id: 'cmp-l2-settings-menu',
    title: 'L2 Settings Menu',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/L2SettingsMenu.vue',
    nextStep: 'Reuse the shared L2SettingsMenu directly and vary only explicit grouped row payload.',
    summary: 'Use this for compact shell settings menus like Hero Fields where grouped options can be expanded or collapsed.',
    prompt: 'Render the L2 Settings Menu from Building Blocks using the same compact panel, grouped rows, checkboxes, and expand/collapse treatment as the canonical menu sample.',
    usedInShells: ['BB Shell', 'File Shell', 'Record Shell'],
    builtFromBbs: ['toggle-row-icons', 'settings-checkbox', 'colors', 'surfaces', 'borders', 'radius', 'spacing'],
  }),
  'widget-settings-menu': defineBuildingBlockDetail({
    id: 'cmp-widget-settings-menu',
    title: 'Widget Settings Menu',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/WidgetSettingsMenu.vue',
    nextStep: 'Reuse the shared WidgetSettingsMenu directly and vary only explicit grouped section payload.',
    summary: 'Use this for the floating widget settings panel with grouped rows, checkboxes, and reorder chevrons.',
    prompt: 'Render the Widget Settings Menu from Building Blocks using the same dark floating panel, grouped section toggle, row labels, checkboxes, and reorder chevrons.',
    usedInShells: ['BB Shell', 'File Shell', 'Record Shell'],
    builtFromBbs: ['toggle-row-icons', 'settings-checkbox', 'colors', 'surfaces', 'borders', 'radius', 'shadows', 'spacing'],
  }),
  'dialog-shell-frame': defineBuildingBlockDetail({
    id: 'cmp-dialog-shell-frame',
    title: 'Dialog Shell Frame',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/DialogShellFrame.vue',
    nextStep: 'Reuse the shared DialogShellFrame directly and vary only explicit header, body, and footer slot content.',
    summary: 'Use this for the outer dialog container that wraps add/edit shell content.',
    prompt: 'Render the Dialog Shell Frame from Building Blocks using the shared dialog frame parent with canonical title-row and footer children.',
    usedInShells: ['Add/Edit Record Shell', 'Add/Edit File Shell', 'Add/Edit BB Shell'],
    builtFromBbs: ['dialog-shell-title-row', 'dialog-shell-footer', 'surfaces', 'borders', 'radius', 'spacing', 'mini-scrollbar'],
    anatomy: ['Dialog card container', 'Header region', 'Scrollable body region', 'Footer/action region'],
  }),
  'add-edit-bb-shell-header-frame': defineBuildingBlockDetail({
    id: 'cmp-add-edit-bb-shell-header-frame',
    title: 'Add/Edit BB Shell Header Frame',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/AddEditBbShellHeaderFrame.vue',
    nextStep: 'Reuse the shared Add/Edit BB shell header frame directly and vary only explicit title, bb code, and search payload.',
    summary: 'Use this for the master Add/Edit BB shell header wrapper that owns the title, bb code input, and search input.',
    prompt: 'Render the Add/Edit BB Shell Header Frame from Building Blocks using the shared header wrapper with record title, bb code input, and search input.',
    usedInShells: ['Add/Edit BB Shell'],
    builtFromBbs: ['record-title', 'bb-code-input', 'search-bar-input', 'spacing'],
    anatomy: ['Title lane', 'BB code input lane', 'Search input lane'],
  }),
  'dialog-shell-title-row': defineBuildingBlockDetail({
    id: 'cmp-dialog-shell-title-row',
    title: 'Dialog Shell Title Row',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/DialogShellTitleRow.vue',
    nextStep: 'Reuse the shared DialogShellTitleRow directly and vary only explicit title/close payload.',
    summary: 'Use this for the top row inside add/edit shell dialogs.',
    prompt: 'Render the Dialog Shell Title Row from Building Blocks using the canonical add/edit shell title row and close-control alignment.',
    usedInShells: ['Add/Edit Record Shell', 'Add/Edit File Shell', 'Add/Edit BB Shell'],
    builtFromBbs: ['page-title', 'colors', 'spacing'],
    anatomy: ['Main title', 'Optional header actions', 'Close icon button'],
  }),
  'dialog-shell-footer': defineBuildingBlockDetail({
    id: 'cmp-dialog-shell-footer',
    title: 'Dialog Shell Footer',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/DialogShellFooter.vue',
    nextStep: 'Reuse the shared DialogShellFooter directly and vary only explicit legend and save-state payload.',
    summary: 'Use this for the footer action row inside add/edit shell dialogs.',
    prompt: 'Render the Dialog Shell Footer from Building Blocks using the canonical save/cancel action lane from the add/edit shell family.',
    usedInShells: ['Add/Edit Record Shell', 'Add/Edit File Shell', 'Add/Edit BB Shell'],
    builtFromBbs: ['b10-button', 'colors', 'surfaces', 'borders', 'radius', 'spacing'],
    anatomy: ['Footer container', 'Primary action', 'Secondary action', 'Optional status/help copy'],
  }),
  'main-menu-row': defineBuildingBlockDetail({
    id: 'cmp-main-menu-row',
    title: 'Main Menu Row',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/MainMenuRow.vue',
    nextStep: 'Reuse the shared MainMenuRow directly and vary only explicit icon and label payload.',
    summary: 'Use this for standard main menu file rows inside the left drawer.',
    prompt: 'Render the Main Menu Row from Building Blocks using the same left-drawer icon and label treatment as the canonical nav row.',
    usedInShells: ['Main Layout'],
    builtFromBbs: ['main-menu-row-icon', 'main-menu-row-label', 'colors', 'surfaces', 'radius', 'spacing'],
  }),
  'main-menu-subgroup-row': defineBuildingBlockDetail({
    id: 'cmp-main-menu-subgroup-row',
    title: 'Main Menu Subgroup Row',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/MainMenuSubgroupRow.vue',
    nextStep: 'Reuse the shared MainMenuSubgroupRow directly and vary only explicit label and expanded payload.',
    summary: 'Use this for grouped left-drawer subsection rows like Shells and workspace groupings.',
    prompt: 'Render the Main Menu Subgroup Row from Building Blocks using the same subgroup title plus expand-collapse chevron treatment as the canonical drawer subgroup row.',
    usedInShells: ['Main Layout'],
    builtFromBbs: ['toggle-row-icons', 'fonts', 'colors', 'spacing'],
  }),
  'eye-icon': defineBuildingBlockDetail({
    id: 'cmp-eye-icon',
    title: 'Eye Icon',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/buttons/EyeIconButton.vue',
    nextStep: 'Reuse the shared EyeIconButton directly in row, card, and BB surfaces.',
    summary: 'Use this for record/view actions in cards and tables where a lightweight visibility control is needed.',
    prompt: 'Render the Eye Icon from Building Blocks using the same lightweight visibility button treatment as the canonical row-view control.',
    usedInShells: ['BB Shell', 'File Shell', 'Record Shell'],
    builtFromBbs: ['colors', 'icon-sizing'],
  }),
  'edit-button': defineBuildingBlockDetail({
    id: 'cmp-edit-button',
    title: 'Edit Button',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/EditButton.vue',
    nextStep: 'Reuse the shared EditButton directly anywhere row and card edit actions need the same compact blue control.',
    summary: 'Use this for compact edit actions in cards and row controls where the blue edit icon treatment is expected.',
    prompt: 'Render the Edit Button from Building Blocks using the shared EditButton component and the same compact blue edit icon treatment as the canonical row-edit control.',
    usedInShells: ['BB Shell', 'File Shell', 'Record Shell'],
    builtFromBbs: ['b10-icon-button', 'colors'],
  }),
  'mini-scrollbar': defineBuildingBlockDetail({
    id: 'cmp-mini-scrollbar',
    title: 'Mini Scrollbar',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/css/app.scss (.ds-mini-scrollbar)',
    nextStep: 'Reuse the shared ds-mini-scrollbar utility directly anywhere dense shell panels need the same narrow scrollbar treatment.',
    summary: 'Use this for the thin black scrollbar treatment that appears in dense shell panels.',
    prompt: 'Render the Mini Scrollbar from Building Blocks using the shared ds-mini-scrollbar utility and the same narrow black scrollbar treatment as the canonical shell overflow control.',
    usedInShells: ['BB Shell', 'Add/Edit BB Shell', 'Add/Edit Record Shell', 'Add/Edit File Shell', 'Record Shell', 'File Shell'],
    builtFromBbs: ['colors'],
  }),
  'collapsible-section-shell': defineBuildingBlockDetail({
    id: 'cmp-collapsible-section-shell',
    title: 'Collapsible Section Shell',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/CollapsibleSectionShell.vue',
    nextStep: 'Reuse the shared section shell directly and vary only explicit title, collapsed state, and body payload.',
    summary: 'Use this for add/edit dialog sections that need a title row with collapse/expand behavior.',
    prompt: 'Render the Collapsible Section Shell from Building Blocks using the shared title row, chevron, and section body wrapper.',
    usedInShells: ['BB Shell', 'Add/Edit Record Shell'],
    builtFromBbs: ['toggle-row-icons', 'colors', 'spacing'],
    anatomy: ['Section title row', 'Expand/collapse chevron', 'Optional actions lane', 'Body wrapper'],
  }),
  'drop-zone': defineBuildingBlockDetail({
    id: 'cmp-drop-zone',
    title: 'Drop Zone',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/DropZone.vue',
    nextStep: 'Reuse the shared drop zone directly and vary only explicit caption, active state, and slotted contents.',
    summary: 'Use this for file and folder staging areas inside add/edit shell dialogs.',
    prompt: 'Render the Drop Zone from Building Blocks using the shared staged-artifact drop area and active drag state.',
    usedInShells: ['BB Shell', 'Add/Edit Record Shell'],
    builtFromBbs: ['surfaces', 'borders', 'radius', 'spacing'],
    anatomy: ['Drop-zone surface', 'Caption copy', 'Active drag state', 'Slotted list/footer area'],
  }),
  'artifact-row': defineBuildingBlockDetail({
    id: 'cmp-artifact-row',
    title: 'Artifact Row',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/ArtifactRow.vue',
    nextStep: 'Reuse the shared artifact row directly and vary only explicit selected state, icon, name, and size payload.',
    summary: 'Use this for staged artifact cards inside add/edit record ingestion areas.',
    prompt: 'Render the Artifact Row from Building Blocks using the shared checkbox, preview icon, name, and size card.',
    usedInShells: ['BB Shell', 'Add/Edit Record Shell'],
    builtFromBbs: ['colors', 'surfaces', 'borders', 'radius', 'spacing'],
    anatomy: ['Selection checkbox', 'Artifact preview', 'Artifact name', 'Artifact size'],
  }),
  'processing-box': defineBuildingBlockDetail({
    id: 'cmp-processing-box',
    title: 'Processing Box',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/ProcessingBox.vue',
    nextStep: 'Reuse the shared processing box directly and vary only explicit title, meta, compact mode, and body payload.',
    summary: 'Use this for ingestion, URL, and blurb sub-panels inside add/edit record processing areas.',
    prompt: 'Render the Processing Box from Building Blocks using the shared compact panel surface and head row.',
    usedInShells: ['BB Shell', 'Add/Edit Record Shell'],
    builtFromBbs: ['surfaces', 'borders', 'radius', 'spacing'],
    anatomy: ['Panel surface', 'Title row', 'Optional meta/actions', 'Body content'],
  }),
  'section-tabs': defineBuildingBlockDetail({
    id: 'cmp-section-tabs',
    title: 'Section Tabs',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/SectionTabs.vue',
    nextStep: 'Reuse the shared section tabs directly and vary only explicit left/right tab payload plus active key.',
    summary: 'Use this for split tab rows in add/edit dialog bodies.',
    prompt: 'Render the Section Tabs from Building Blocks using the shared split left/right tab row from the add/edit record shell.',
    usedInShells: ['BB Shell', 'Add/Edit Record Shell'],
    builtFromBbs: ['colors', 'surfaces', 'borders', 'radius', 'spacing'],
    anatomy: ['Left tab lane', 'Right tab lane', 'Active tab state'],
  }),
  'shell-selector': defineBuildingBlockDetail({
    id: 'cmp-shell-selector',
    title: 'Shell Selector',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/ShellSelector.vue',
    nextStep: 'Reuse the shared shell selector directly and vary only explicit options and selected shell payload.',
    summary: 'Use this for compact shell-type selectors in add/edit dialog headers.',
    prompt: 'Render the Shell Selector from Building Blocks using the shared compact chip selector built from the current chip and chevron family.',
    usedInShells: ['BB Shell', 'Add/Edit Record Shell'],
    builtFromBbs: ['value-chip-surface', 'dropdown-chevron', 'colors', 'spacing'],
    anatomy: ['Selected shell chip', 'Chevron affordance', 'Dropdown menu options'],
  }),
  'field-map-row': defineBuildingBlockDetail({
    id: 'cmp-field-map-row',
    title: 'Field Map Row',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/FieldMapRow.vue',
    nextStep: 'Reuse the shared field map row directly and vary only explicit label, type hint, wide state, and slotted input/action content.',
    summary: 'Use this for canonical field rows in add/edit record shell mapping panels.',
    prompt: 'Render the Field Map Row from Building Blocks using the shared label lane, input lane, and verification-action lane from the add/edit record shell.',
    usedInShells: ['BB Shell', 'Add/Edit Record Shell'],
    builtFromBbs: ['record-field-status-icon', 'colors', 'spacing'],
    anatomy: ['Field label lane', 'Optional parent-link slot', 'Input/content lane', 'Verification-action slot'],
  }),
  'entry-input-list-box': defineBuildingBlockDetail({
    id: 'cmp-entry-input-list-box',
    title: 'Entry Input List Box',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/EntryInputListBox.vue',
    nextStep: 'Reuse the shared entry input list box directly and vary only explicit input value, entries, selection, and expanded payload.',
    summary: 'Use this for compact add-and-select entry lists such as URLs and Blurbs in add/edit record shell.',
    prompt: 'Render the Entry Input List Box from Building Blocks using the shared one-line input plus selectable entry list pattern.',
    usedInShells: ['BB Shell', 'Add/Edit Record Shell'],
    builtFromBbs: ['colors', 'surfaces', 'borders', 'spacing'],
    anatomy: ['Inline text input', 'Selectable entry list', 'Expandable entry rows'],
  }),
  'editable-grid-table': defineBuildingBlockDetail({
    id: 'cmp-editable-grid-table',
    title: 'Editable Grid Table',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/EditableGridTable.vue',
    nextStep: 'Reuse the shared editable grid table directly and vary only explicit rows, columns, and edit permissions.',
    summary: 'Use this for editable section-configuration tables in add/edit file shell.',
    prompt: 'Render the Editable Grid Table from Building Blocks using the shared dynamic row/column configuration table from add/edit file shell.',
    usedInShells: ['BB Shell', 'Add/Edit File Shell'],
    builtFromBbs: ['mini-scrollbar', 'colors', 'surfaces', 'borders', 'radius', 'spacing'],
    anatomy: ['Dynamic columns', 'Dynamic rows', 'Add controls', 'Delete controls', 'Framed placeholder cells'],
  }),
  'bb-selection-frame': defineBuildingBlockDetail({
    id: 'cmp-bb-selection-frame',
    title: 'BB Selection Frame',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/BbSelectionFrame.vue',
    nextStep: 'Reuse the shared BB Selection Frame directly and vary only the selected BB content rendered inside it.',
    summary: 'Use this for the framed stage that renders BB selections below tabs and search in the Add/Edit BB flow.',
    prompt: 'Render the BB Selection Frame from Building Blocks as the quiet framed area that hosts selected BB results.',
    usedInShells: ['BB Shell', 'Add/Edit BB Shell'],
    builtFromBbs: ['colors', 'surfaces', 'borders', 'radius', 'spacing'],
    anatomy: ['Framed selection stage', 'Quiet bordered surface', 'Scrollable content area'],
  }),
  'bb-render-frame': defineBuildingBlockDetail({
    id: 'cmp-bb-render-frame',
    title: 'BB Render Frame',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/BbRenderFrame.vue',
    nextStep: 'Reuse the shared BB Render Frame directly and vary only the selected BB rendered inside it.',
    summary: 'Use this for the framed render stage that displays the selected BB above the subgroup labels.',
    prompt: 'Render the BB Render Frame from Building Blocks as the bordered staging area that hosts the selected BB output.',
    usedInShells: ['BB Shell', 'Add/Edit BB Shell'],
    builtFromBbs: ['colors', 'surfaces', 'borders', 'radius', 'spacing'],
    anatomy: ['Framed render stage', 'Quiet bordered surface', 'Expandable content area'],
  }),
  'toggle-row-icons': defineBuildingBlockDetail({
    id: 'cmp-toggle-row-icons',
    title: 'Toggle / Row Icons',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/ToggleRowIcons.vue',
    nextStep: 'Reuse the shared ToggleRowIcons directly and vary only explicit label, direction, and tone payload.',
    summary: 'Use this for inline subgroup toggles and row ordering chevrons across shell menus and settings lists.',
    prompt: 'Render the Toggle / Row Icons from Building Blocks using the same inline label-plus-chevron and compact row-chevron treatments as the canonical controls.',
    usedInShells: ['BB Shell', 'File Shell', 'Record Shell'],
    builtFromBbs: ['colors', 'icon-sizing'],
  }),
  'shell-open-dialog-button': defineBuildingBlockDetail({
    id: 'cmp-shell-open-dialog-button',
    title: 'Shell Open Dialog Button',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/ShellOpenDialogButton.vue',
    nextStep: 'Reuse the shared ShellOpenDialogButton directly and vary only the route-kind payload.',
    summary: 'Use this for shell-specific buttons that reopen or launch the active shell dialog.',
    prompt: 'Render the Shell Open Dialog Button from Building Blocks using the canonical shell launch button treatment with route-aware behavior.',
    usedInShells: ['Add/Edit Record Shell', 'Add/Edit File Shell', 'Add/Edit BB Shell', 'Fork Shell'],
    builtFromBbs: ['value-chip-surface', 'value-chip-label'],
    anatomy: ['Button container', 'Action label', 'Shell-aware open behavior'],
  }),
  'file-filter-menu': defineBuildingBlockDetail({
    id: 'cmp-file-filter-menu',
    title: 'File Filter Menu',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/FileFilterMenu.vue',
    nextStep: 'Reuse the shared FileFilterMenu directly and vary only the explicit grouped filter payload.',
    summary: 'Use this for the file-shell filter menu with grouped sections, token rows, and checkboxes.',
    prompt: 'Render the File Filter Menu from Building Blocks using the same grouped filter panel, section headings, token rows, and checkbox treatment as the current file shell.',
    usedInShells: ['File Shell', 'BB Shell'],
    builtFromBbs: ['toggle-row-icons', 'settings-checkbox', 'colors', 'surfaces', 'borders', 'radius', 'spacing'],
    anatomy: ['Filter panel title', 'Grouped section headings', 'Token rows', 'Checkbox controls'],
  }),
  'fork-selector-surface': defineBuildingBlockDetail({
    id: 'cmp-fork-selector-surface',
    title: 'Fork Selector Surface',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/ForkSelectorSurface.vue',
    nextStep: 'Reuse the shared ForkSelectorSurface directly and vary only explicit branchable selector payload.',
    summary: 'Use this for the black value-chip selector that sits above the fork shell card and switches the active branchable L1.',
    prompt: 'Render the Fork Selector Surface from Building Blocks using the same top selector surface from Fork Shell, including the hover label and black selected-value chip.',
    usedInShells: ['Fork Shell'],
    builtFromBbs: ['live-action-l1', 'colors', 'spacing'],
    anatomy: ['Hover label', 'Selected value chip', 'Dropdown surface'],
  }),
  'fork-branch-card': defineBuildingBlockDetail({
    id: 'cmp-fork-branch-card',
    title: 'Fork Branch Card',
    status: 'canonical',
    statusLabel: 'Canonical Shared',
    source: 'src/components/ForkBranchCard.vue',
    nextStep: 'Reuse the shared ForkBranchCard directly and vary only explicit branch label payload.',
    summary: 'Use this for the selectable branch options inside Fork Shell.',
    prompt: 'Render the Fork Branch Card from Building Blocks using the shared fork branch option built from the canonical b10-button family.',
    usedInShells: ['Fork Shell'],
    builtFromBbs: ['b10-button'],
    anatomy: ['Branch option control', 'Branch label', 'Shared button-family surface'],
  }),
}

export const BUILDING_BLOCK_OPTIONS = Object.entries(BUILDING_BLOCK_DETAILS_BY_ID)
  .filter(([, detail]) => detail.status !== 'deprecated')
  .map(([value, detail]) => ({
    label: detail.title,
    value,
  }))

export const BUILDING_BLOCK_SIZE_BY_ID = Object.freeze({
  fonts: 'full-row',
  'type-scale': 'full-row',
  'font-weights': 'lg',
  colors: 'full-row',
  surfaces: 'full-row',
  borders: 'lg',
  radius: 'lg',
  shadows: 'lg',
  spacing: 'full-row',
  'icon-sizing': 'lg',
  'formatting-rules': 'full-row',
  'motion-rules': 'full-row',
  'b10-logo': 'sm',
  'b10-button': 'md',
  'b10-icon-button': 'md',
  'view-mode-toggle': 'md',
  'filter-list-icon': 'sm',
  'search-bar-input': 'md',
  'bb-code-input': 'md',
  'settings-checkbox': 'sm',
  'main-menu-icon': 'md',
  'main-menu-row-icon': 'sm',
  'main-menu-row-label': 'md',
  'value-chip-surface': 'md',
  'value-chip-label': 'sm',
  'button-label': 'sm',
  'value-chip': 'md',
  'dropdown-chevron': 'sm',
  'page-title': 'title-wide',
  'record-title': 'title-wide',
  'west-icon': 'sm',
  'page-back-label': 'sm',
  'page-back-symbol': 'md',
  'shell-title-row': 'toolbar-wide',
  'main-menu-row': 'toolbar-wide',
  'main-menu-subgroup-row': 'toolbar-wide',
  'live-action-l1': 'live-link',
  'l2-toolbar': 'full-row',
  'l2-settings-menu': 'settings-menu',
  'widget-settings-menu': 'widget-settings',
  'dialog-shell-frame': 'full-row',
  'add-edit-bb-shell-header-frame': 'toolbar-wide',
  'dialog-shell-title-row': 'toolbar-wide',
  'dialog-shell-footer': 'toolbar-wide',
  'toggle-row-icons': 'md',
  'shell-open-dialog-button': 'md',
  'plus-icon': 'sm',
  'plus-with-label': 'md',
  'bb-tile-header': 'toolbar-wide',
  'eye-icon': 'sm',
  'edit-button': 'sm',
  'mini-scrollbar': 'md',
  'collapsible-section-shell': 'toolbar-wide',
  'drop-zone': 'md',
  'artifact-row': 'sm',
  'processing-box': 'md',
  'section-tabs': 'toolbar-wide',
  'shell-selector': 'md',
  'field-map-row': 'toolbar-wide',
  'entry-input-list-box': 'md',
  'editable-grid-table': 'full-row',
  'bb-selection-frame': 'full-row',
  'bb-render-frame': 'full-row',
  'home-dashboard': 'full-row',
  'record-hero': 'full-row',
  'hero-surface': 'full-row',
  'hero-3col-overlay': 'full-row',
  'hero-2col-overlay': 'full-row',
  'file-hero': 'full-row',
  'l3-box': 'stat-box',
  'file-toolbar': 'full-row',
  'record-hero-field-card': 'md',
  'record-field-label': 'sm',
  'record-field-description': 'sm',
  'record-field-value': 'sm',
  'record-fields-box': 'toolbar-wide',
  'record-summary-box': 'md',
  'record-field-status-icon': 'sm',
  'record-context-panel': 'toolbar-wide',
  'record-feed-panel': 'toolbar-wide',
  'record-feed-label': 'sm',
  'record-feed-tab-label': 'sm',
  'record-feed-time': 'sm',
  'record-feed-entry-title': 'sm',
  'record-feed-empty': 'sm',
  'record-feed-entry-surface': 'md',
  'file-filter-menu': 'settings-menu',
  'fork-selector-surface': 'live-link',
  'fork-branch-card': 'md',
})

export function getBuildingBlockTileSize(blockId) {
  return BUILDING_BLOCK_SIZE_BY_ID[String(blockId || '').trim()] || 'md'
}

const BUILDING_BLOCK_CATEGORY_BY_ID = Object.freeze({
  fonts: 'Basic Elements',
  'type-scale': 'Basic Elements',
  'font-weights': 'Basic Elements',
  colors: 'Basic Elements',
  surfaces: 'Basic Elements',
  borders: 'Basic Elements',
  radius: 'Basic Elements',
  shadows: 'Basic Elements',
  spacing: 'Basic Elements',
  'icon-sizing': 'Basic Elements',
  'formatting-rules': 'Basic Elements',
  'motion-rules': 'Basic Elements',
  'b10-logo': 'Basic Elements',
  'b10-button': 'Basic Elements',
  'b10-icon-button': 'Basic Elements',
  'view-mode-toggle': 'Basic Elements',
  'filter-list-icon': 'Basic Elements',
  'search-bar-input': 'Basic Elements',
  'bb-code-input': 'Dialog Components',
  'settings-checkbox': 'Basic Elements',
  'main-menu-icon': 'Basic Elements',
  'main-menu-row-icon': 'Navigation Components',
  'main-menu-row-label': 'Navigation Components',
  'value-chip-surface': 'Navigation Components',
  'value-chip-label': 'Navigation Components',
  'button-label': 'Basic Elements',
  'value-chip': 'Navigation Components',
  'dropdown-chevron': 'Navigation Components',
  'page-title': 'Navigation Components',
  'record-title': 'Record Components',
  'west-icon': 'Navigation Components',
  'page-back-label': 'Navigation Components',
  'page-back-symbol': 'Navigation Components',
  'shell-title-row': 'Navigation Components',
  'main-menu-row': 'Navigation Components',
  'main-menu-subgroup-row': 'Navigation Components',
  'live-action-l1': 'Navigation Components',
  'l2-toolbar': 'Navigation Components',
  'l2-settings-menu': 'Navigation Components',
  'widget-settings-menu': 'Navigation Components',
  'toggle-row-icons': 'Navigation Components',
  'plus-icon': 'Dialog Components',
  'plus-with-label': 'Dialog Components',
  'bb-tile-header': 'Dialog Components',
  'dialog-shell-frame': 'Dialog Components',
  'add-edit-bb-shell-header-frame': 'Dialog Components',
  'dialog-shell-title-row': 'Dialog Components',
  'dialog-shell-footer': 'Dialog Components',
  'eye-icon': 'Dialog Components',
  'edit-button': 'Dialog Components',
  'mini-scrollbar': 'Dialog Components',
  'collapsible-section-shell': 'Dialog Components',
  'drop-zone': 'Dialog Components',
  'artifact-row': 'Dialog Components',
  'processing-box': 'Dialog Components',
  'section-tabs': 'Dialog Components',
  'shell-selector': 'Dialog Components',
  'field-map-row': 'Dialog Components',
  'entry-input-list-box': 'Dialog Components',
  'editable-grid-table': 'Dialog Components',
  'bb-selection-frame': 'Dialog Components',
  'bb-render-frame': 'Dialog Components',
  'home-dashboard': 'File Components',
  'l3-box': 'File Components',
  'file-toolbar': 'File Components',
  'file-filter-menu': 'File Components',
  'record-hero': 'Record Components',
  'hero-surface': 'Record Components',
  'hero-3col-overlay': 'Record Components',
  'hero-2col-overlay': 'Record Components',
  'record-hero-field-card': 'Record Components',
  'record-field-label': 'Record Components',
  'record-field-description': 'Record Components',
  'record-field-value': 'Record Components',
  'record-fields-box': 'Record Components',
  'record-summary-box': 'Record Components',
  'file-hero': 'Record Components',
  'record-field-status-icon': 'Record Components',
  'record-context-panel': 'Record Components',
  'record-feed-panel': 'Record Components',
  'record-feed-label': 'Record Components',
  'record-feed-tab-label': 'Record Components',
  'record-feed-time': 'Record Components',
  'record-feed-entry-title': 'Record Components',
  'record-feed-empty': 'Record Components',
  'record-feed-entry-surface': 'Record Components',
  'shell-open-dialog-button': 'Shell Components',
  'fork-selector-surface': 'Shell Components',
  'fork-branch-card': 'Shell Components',
})

export const DEFAULT_BUILDING_BLOCK_FILE_ROWS = Object.entries(BUILDING_BLOCK_DETAILS_BY_ID)
  .filter(([, detail]) => detail.status !== 'deprecated')
  .map(([blockKey, detail], index) => ({
    id: `bb:${blockKey}`,
    Sort_Order: index + 1,
    Name: detail.title,
    Summary: detail.summary || '',
    Category: BUILDING_BLOCK_CATEGORY_BY_ID[blockKey] || 'Building Blocks',
    Status: detail.statusLabel || detail.status || '',
    Used_In: Array.isArray(detail.usedIn) ? detail.usedIn.join('\n') : '',
    Used_In_Shells: Array.isArray(detail.usedInShells) ? detail.usedInShells.join('\n') : '',
    Use_When: detail.summary || '',
    Avoid_When: '',
    Built_From_BBs: Array.isArray(detail.builtFromBbs) ? detail.builtFromBbs.join('\n') : '',
    Convergence_Rule: Array.isArray(detail.convergenceRule) ? detail.convergenceRule.join('\n') : '',
    Anatomy: Array.isArray(detail.anatomy) ? detail.anatomy.join('\n') : '',
    Required_Parts: Array.isArray(detail.anatomy) ? detail.anatomy.join('\n') : '',
    Source_Path: detail.source || '',
    Owner: 'BB Shell',
    Extraction_Status: detail.statusLabel || '',
    Reconstruction_Notes: Array.isArray(detail.reconstructionNotes) ? detail.reconstructionNotes.join('\n') : '',
    Prompt: detail.prompt || '',
    Variants: detail.status === 'canonical' ? 'Canonical Shared' : 'Extract Next',
  }))

export function getBuildingBlockDetail(blockId) {
  return BUILDING_BLOCK_DETAILS_BY_ID[String(blockId || '').trim()] || null
}

function getDependencyMatchValues(blockKey, detail) {
  return new Set(
    [String(blockKey || '').trim(), detail?.id, detail?.title]
      .map((value) => String(value || '').trim())
      .filter(Boolean),
  )
}

export function getBuildingBlockGraphCounts(blockId) {
  const normalizedBlockId = String(blockId || '').trim()
  const detail = getBuildingBlockDetail(normalizedBlockId)
  if (!detail) {
    return { parentCount: 0, childCount: 0 }
  }

  const matchValues = getDependencyMatchValues(normalizedBlockId, detail)
  const childCount = Array.isArray(detail.builtFromBbs) ? detail.builtFromBbs.filter(Boolean).length : 0

  const parentCount = Object.entries(BUILDING_BLOCK_DETAILS_BY_ID).reduce((count, [, candidateDetail]) => {
    const dependencies = Array.isArray(candidateDetail?.builtFromBbs) ? candidateDetail.builtFromBbs : []
    return dependencies.some((dependency) => matchValues.has(String(dependency || '').trim()))
      ? count + 1
      : count
  }, 0)

  return { parentCount, childCount }
}

export function getBuildingBlockGraphLinks(blockId) {
  const normalizedBlockId = String(blockId || '').trim()
  const detail = getBuildingBlockDetail(normalizedBlockId)
  if (!detail) {
    return { parents: [], children: [] }
  }

  const matchValues = getDependencyMatchValues(normalizedBlockId, detail)
  const children = (Array.isArray(detail.builtFromBbs) ? detail.builtFromBbs : [])
    .map((dependency) => {
      const normalizedDependency = String(dependency || '').trim()
      const childDetail = getBuildingBlockDetail(normalizedDependency)
      if (!normalizedDependency) return null
      return {
        blockKey: normalizedDependency,
        title: childDetail?.title || normalizedDependency,
      }
    })
    .filter(Boolean)

  const parents = Object.entries(BUILDING_BLOCK_DETAILS_BY_ID)
    .filter(([, candidateDetail]) => {
      const dependencies = Array.isArray(candidateDetail?.builtFromBbs) ? candidateDetail.builtFromBbs : []
      return dependencies.some((dependency) => matchValues.has(String(dependency || '').trim()))
    })
    .map(([candidateKey, candidateDetail]) => ({
      blockKey: candidateKey,
      title: candidateDetail?.title || candidateKey,
    }))

  return { parents, children }
}
