export const DEFAULT_PERSONALIZE_ROWS = Object.freeze([
  Object.freeze({
    id: 'utils:fonts',
    Sort_Order: 10,
    Name: 'Fonts',
    Summary: 'Title and body font choices for the workspace.',
    Category: 'Basic Elements',
    Status: 'Active',
    Used_In: 'Personalize',
    Used_In_Shells: 'LDB Files',
    Use_When: 'Adjusting title and body font choices for the current workspace.',
    Avoid_When: 'Changing record or file data instead of presentation.',
    Built_From_BBs: null,
    Anatomy: 'Title font, body font',
    Required_Parts: 'Title font, body font',
    Source_Path: 'src/css/tokens.scss',
    Owner: 'Personalize',
    Extraction_Status: 'Canonical',
    Reconstruction_Notes: 'Keep this focused on live personalization choices only.',
    Convergence_Rule: 'Personalize should expose only live presentation settings.',
    Prompt: 'Show the live font choices for the workspace.',
    Variants: null,
  }),
  Object.freeze({
    id: 'utils:colors',
    Sort_Order: 20,
    Name: 'Primary Colors',
    Summary: 'Primary workspace color choices for the live interface.',
    Category: 'Basic Elements',
    Status: 'Active',
    Used_In: 'Personalize',
    Used_In_Shells: 'LDB Files',
    Use_When: 'Adjusting the main workspace color treatment.',
    Avoid_When: 'Changing semantic record data instead of presentation.',
    Built_From_BBs: null,
    Anatomy: 'Primary brand color, supporting primary color',
    Required_Parts: 'Primary brand color',
    Source_Path: 'src/css/tokens.scss',
    Owner: 'Personalize',
    Extraction_Status: 'Canonical',
    Reconstruction_Notes: 'Keep this focused on live personalization choices only.',
    Convergence_Rule: 'Personalize should expose only live presentation settings.',
    Prompt: 'Show the live primary color choices for the workspace.',
    Variants: null,
  }),
])
